---
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  # Changelog
  $CHANGES

  See details of [all code changes](https://github.com/sophos-internal/labs.qa.aws-client/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION) since previous release

categories:
  - title: Exciting New Features 🎉
    labels:
      - enhancement
      - feature
      - flaui-wrappers
      - flaui-core
      - flaui-lib
      - flaui-c-sharp-binaries

  - title: Breaking Changes 🛠
    labels:
      - breaking-change
      - breaking

  - title: Bug Fixes 🐛
    labels:
      - bug
      - fix

  - title: Documentation Changes 📚
    labels:
      - documentation
      - docs

  - title: Dependency Updates 📦
    labels:
      - dependency-update

  - title: CI/CD Changes 🚀
    labels:
      - ci-cd

  - title: Configuration Changes ⚙️
    labels:
      - configuration

  - title: Tests 🧪
    labels:
      - tests

  - title: Other Changes
    labels:
      - "*"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: minor
