from __future__ import annotations

from typing import Any
from typing import List
from typing import Type

import System
import System.Collections
import System.ComponentModel
import System.Configuration
import System.Configuration.Assemblies
import System.Data
import System.Globalization
import System.IO
import System.Reflection
import System.Runtime
import System.Runtime.CompilerServices
import System.Runtime.InteropServices
import System.Runtime.Remoting
import System.Runtime.Serialization
import System.Security
import System.Security.AccessControl
import System.Security.Cryptography
import System.Security.Cryptography.X509Certificates
import System.Security.Policy
import System.Security.Principal
import System.Threading
import System.Threading.Tasks
import System.Xml
import System.Xml.Schema
import System.Xml.Serialization
from System.ComponentModel import MarshalByValueComponent


class IOverlayManager:

    def __init__(self, *args, **kwargs) -> Any: ...
    def Dispose(self) -> None: ...

    @property
    def Margin(self): ...

    @Margin.setter
    def Margin(self, value): ...

    def Show(
            self,
            _: System.Drawing.Rectangle,
            __: System.Drawing.Color,
            ___: int,
            ) -> None: ...

    def ShowBlocking(
            self,
            _: System.Drawing.Rectangle,
            __: System.Drawing.Color,
            ___: int,
            ) -> None: ...

    @property
    def Size(self): ...

    @Size.setter
    def Size(self, value): ...

    def get_Margin(self) -> int: ...
    def get_Size(self) -> int: ...
    def set_Margin(self, _: int) -> None: ...
    def set_Size(self, _: int) -> None: ...


class NullOverlayManager:

    def __init__(self, *args, **kwargs) -> Any: ...
    def Dispose(self) -> None: ...
    def Equals(self, _: object, __: object) -> bool: ...
    def Finalize(self) -> None: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...

    @property
    def Margin(self): ...

    @Margin.setter
    def Margin(self, value): ...

    def MemberwiseClone(self) -> object: ...
    def Overloads(self, *args, **kwargs) -> Any: ...
    def ReferenceEquals(self, _: object, __: object) -> bool: ...

    def Show(
            self,
            _: System.Drawing.Rectangle,
            __: System.Drawing.Color,
            ___: int,
            ) -> None: ...

    def ShowBlocking(
            self,
            _: System.Drawing.Rectangle,
            __: System.Drawing.Color,
            ___: int,
            ) -> None: ...

    @property
    def Size(self): ...

    @Size.setter
    def Size(self, value): ...

    def ToString(self) -> str: ...
    def get_Margin(self) -> int: ...
    def get_Size(self) -> int: ...
    def set_Margin(self, _: int) -> None: ...
    def set_Size(self, _: int) -> None: ...


class OverlayRectangleForm:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def AcceptButton(self): ...

    @AcceptButton.setter
    def AcceptButton(self, value): ...

    def AccessibilityNotifyClients(
            self,
            _: System.Windows.Forms.AccessibleEvents,
            __: int,
            ___: int,
            ) -> None: ...

    @property
    def AccessibilityObject(self): ...

    @AccessibilityObject.setter
    def AccessibilityObject(self, value): ...

    @property
    def AccessibleDefaultActionDescription(self): ...

    @AccessibleDefaultActionDescription.setter
    def AccessibleDefaultActionDescription(self, value): ...

    @property
    def AccessibleDescription(self): ...

    @AccessibleDescription.setter
    def AccessibleDescription(self, value): ...

    @property
    def AccessibleName(self): ...

    @AccessibleName.setter
    def AccessibleName(self, value): ...

    @property
    def AccessibleRole(self): ...

    @AccessibleRole.setter
    def AccessibleRole(self, value): ...

    def Activate(self) -> None: ...
    def ActivateMdiChild(self, _: System.Windows.Forms.Form) -> None: ...
    def Activated(self, *args, **kwargs) -> Any: ...

    @property
    def ActiveControl(self): ...

    @ActiveControl.setter
    def ActiveControl(self, value): ...

    def ActiveForm(self, *args, **kwargs) -> Any: ...

    @property
    def ActiveMdiChild(self): ...

    @ActiveMdiChild.setter
    def ActiveMdiChild(self, value): ...

    def AddOwnedForm(self, _: System.Windows.Forms.Form) -> None: ...
    def AdjustFormScrollbars(self, _: bool) -> None: ...

    @property
    def AllowDrop(self): ...

    @AllowDrop.setter
    def AllowDrop(self, value): ...

    @property
    def AllowTransparency(self): ...

    @AllowTransparency.setter
    def AllowTransparency(self, value): ...

    @property
    def Anchor(self): ...

    @Anchor.setter
    def Anchor(self, value): ...

    def ApplyAutoScaling(self) -> None: ...

    @property
    def AutoScale(self): ...

    @AutoScale.setter
    def AutoScale(self, value): ...

    @property
    def AutoScaleBaseSize(self): ...

    @AutoScaleBaseSize.setter
    def AutoScaleBaseSize(self, value): ...

    @property
    def AutoScaleDimensions(self): ...

    @AutoScaleDimensions.setter
    def AutoScaleDimensions(self, value): ...

    @property
    def AutoScaleFactor(self): ...

    @AutoScaleFactor.setter
    def AutoScaleFactor(self, value): ...

    @property
    def AutoScaleMode(self): ...

    @AutoScaleMode.setter
    def AutoScaleMode(self, value): ...

    @property
    def AutoScroll(self): ...

    @AutoScroll.setter
    def AutoScroll(self, value): ...

    @property
    def AutoScrollMargin(self): ...

    @AutoScrollMargin.setter
    def AutoScrollMargin(self, value): ...

    @property
    def AutoScrollMinSize(self): ...

    @AutoScrollMinSize.setter
    def AutoScrollMinSize(self, value): ...

    @property
    def AutoScrollOffset(self): ...

    @AutoScrollOffset.setter
    def AutoScrollOffset(self, value): ...

    @property
    def AutoScrollPosition(self): ...

    @AutoScrollPosition.setter
    def AutoScrollPosition(self, value): ...

    @property
    def AutoSize(self): ...

    @AutoSize.setter
    def AutoSize(self, value): ...

    def AutoSizeChanged(self, *args, **kwargs) -> Any: ...

    @property
    def AutoSizeMode(self): ...

    @AutoSizeMode.setter
    def AutoSizeMode(self, value): ...

    @property
    def AutoValidate(self): ...

    @AutoValidate.setter
    def AutoValidate(self, value): ...

    def AutoValidateChanged(self, *args, **kwargs) -> Any: ...

    @property
    def BackColor(self): ...

    @BackColor.setter
    def BackColor(self, value): ...

    def BackColorChanged(self, *args, **kwargs) -> Any: ...

    @property
    def BackgroundImage(self): ...

    @BackgroundImage.setter
    def BackgroundImage(self, value): ...

    def BackgroundImageChanged(self, *args, **kwargs) -> Any: ...

    @property
    def BackgroundImageLayout(self): ...

    @BackgroundImageLayout.setter
    def BackgroundImageLayout(self, value): ...

    def BackgroundImageLayoutChanged(self, *args, **kwargs) -> Any: ...
    def BeginInvoke(self, _: Any, __: List[object]) -> Any: ...

    @property
    def BindingContext(self): ...

    @BindingContext.setter
    def BindingContext(self, value): ...

    def BindingContextChanged(self, *args, **kwargs) -> Any: ...

    @property
    def Bottom(self): ...

    @Bottom.setter
    def Bottom(self, value): ...

    @property
    def Bounds(self): ...

    @Bounds.setter
    def Bounds(self, value): ...

    def BringToFront(self) -> None: ...

    @property
    def CanEnableIme(self): ...

    @CanEnableIme.setter
    def CanEnableIme(self, value): ...

    @property
    def CanFocus(self): ...

    @CanFocus.setter
    def CanFocus(self, value): ...

    @property
    def CanRaiseEvents(self): ...

    @CanRaiseEvents.setter
    def CanRaiseEvents(self, value): ...

    @property
    def CanSelect(self): ...

    @CanSelect.setter
    def CanSelect(self, value): ...

    @property
    def CancelButton(self): ...

    @CancelButton.setter
    def CancelButton(self, value): ...

    @property
    def Capture(self): ...

    @Capture.setter
    def Capture(self, value): ...

    @property
    def CausesValidation(self): ...

    @CausesValidation.setter
    def CausesValidation(self, value): ...

    def CausesValidationChanged(self, *args, **kwargs) -> Any: ...
    def CenterToParent(self) -> None: ...
    def CenterToScreen(self) -> None: ...
    def ChangeUICues(self, *args, **kwargs) -> Any: ...
    def CheckForIllegalCrossThreadCalls(self, *args, **kwargs) -> Any: ...
    def Click(self, *args, **kwargs) -> Any: ...

    @property
    def ClientRectangle(self): ...

    @ClientRectangle.setter
    def ClientRectangle(self, value): ...

    @property
    def ClientSize(self): ...

    @ClientSize.setter
    def ClientSize(self, value): ...

    def ClientSizeChanged(self, *args, **kwargs) -> Any: ...
    def Close(self) -> None: ...
    def Closed(self, *args, **kwargs) -> Any: ...
    def Closing(self, *args, **kwargs) -> Any: ...

    @property
    def CompanyName(self): ...

    @CompanyName.setter
    def CompanyName(self, value): ...

    @property
    def Container(self): ...

    @Container.setter
    def Container(self, value): ...

    def Contains(self, _: System.Windows.Forms.Control) -> bool: ...

    @property
    def ContainsFocus(self): ...

    @ContainsFocus.setter
    def ContainsFocus(self, value): ...

    @property
    def ContextMenu(self): ...

    @ContextMenu.setter
    def ContextMenu(self, value): ...

    def ContextMenuChanged(self, *args, **kwargs) -> Any: ...

    @property
    def ContextMenuStrip(self): ...

    @ContextMenuStrip.setter
    def ContextMenuStrip(self, value): ...

    def ContextMenuStripChanged(self, *args, **kwargs) -> Any: ...
    def ControlAccessibleObject(self, *args, **kwargs) -> Any: ...
    def ControlAdded(self, *args, **kwargs) -> Any: ...

    @property
    def ControlBox(self): ...

    @ControlBox.setter
    def ControlBox(self, value): ...

    def ControlCollection(self, *args, **kwargs) -> Any: ...
    def ControlRemoved(self, *args, **kwargs) -> Any: ...

    @property
    def Controls(self): ...

    @Controls.setter
    def Controls(self, value): ...

    def CreateAccessibilityInstance(self) -> System.Windows.Forms.AccessibleObject: ...
    def CreateControl(self) -> None: ...
    def CreateControlsInstance(self) -> Any: ...
    def CreateGraphics(self) -> System.Drawing.Graphics: ...
    def CreateHandle(self) -> None: ...
    def CreateObjRef(self, _: Type) -> System.Runtime.Remoting.ObjRef: ...

    @property
    def CreateParams(self): ...

    @CreateParams.setter
    def CreateParams(self, value): ...

    @property
    def Created(self): ...

    @Created.setter
    def Created(self, value): ...

    @property
    def CurrentAutoScaleDimensions(self): ...

    @CurrentAutoScaleDimensions.setter
    def CurrentAutoScaleDimensions(self, value): ...

    @property
    def Cursor(self): ...

    @Cursor.setter
    def Cursor(self, value): ...

    def CursorChanged(self, *args, **kwargs) -> Any: ...

    @property
    def DataBindings(self): ...

    @DataBindings.setter
    def DataBindings(self, value): ...

    def Deactivate(self, *args, **kwargs) -> Any: ...
    def DefWndProc(self, _: System.Windows.Forms.Message) -> None: ...
    def DefaultBackColor(self, *args, **kwargs) -> Any: ...

    @property
    def DefaultCursor(self): ...

    @DefaultCursor.setter
    def DefaultCursor(self, value): ...

    def DefaultFont(self, *args, **kwargs) -> Any: ...
    def DefaultForeColor(self, *args, **kwargs) -> Any: ...

    @property
    def DefaultImeMode(self): ...

    @DefaultImeMode.setter
    def DefaultImeMode(self, value): ...

    @property
    def DefaultMargin(self): ...

    @DefaultMargin.setter
    def DefaultMargin(self, value): ...

    @property
    def DefaultMaximumSize(self): ...

    @DefaultMaximumSize.setter
    def DefaultMaximumSize(self, value): ...

    @property
    def DefaultMinimumSize(self): ...

    @DefaultMinimumSize.setter
    def DefaultMinimumSize(self, value): ...

    @property
    def DefaultPadding(self): ...

    @DefaultPadding.setter
    def DefaultPadding(self, value): ...

    @property
    def DefaultSize(self): ...

    @DefaultSize.setter
    def DefaultSize(self, value): ...

    @property
    def DesignMode(self): ...

    @DesignMode.setter
    def DesignMode(self, value): ...

    @property
    def DesktopBounds(self): ...

    @DesktopBounds.setter
    def DesktopBounds(self, value): ...

    @property
    def DesktopLocation(self): ...

    @DesktopLocation.setter
    def DesktopLocation(self, value): ...

    def DestroyHandle(self) -> None: ...

    @property
    def DeviceDpi(self): ...

    @DeviceDpi.setter
    def DeviceDpi(self, value): ...

    @property
    def DialogResult(self): ...

    @DialogResult.setter
    def DialogResult(self, value): ...

    @property
    def DisplayRectangle(self): ...

    @DisplayRectangle.setter
    def DisplayRectangle(self, value): ...

    def Dispose(self) -> None: ...
    def Disposed(self, *args, **kwargs) -> Any: ...

    @property
    def Disposing(self): ...

    @Disposing.setter
    def Disposing(self, value): ...

    def DoDragDrop(
            self,
            _: object,
            __: System.Windows.Forms.DragDropEffects,
            ) -> System.Windows.Forms.DragDropEffects: ...

    @property
    def Dock(self): ...

    @Dock.setter
    def Dock(self, value): ...

    def DockChanged(self, *args, **kwargs) -> Any: ...

    @property
    def DockPadding(self): ...

    @DockPadding.setter
    def DockPadding(self, value): ...

    def DockPaddingEdges(self, *args, **kwargs) -> Any: ...
    def DockPaddingEdgesConverter(self, *args, **kwargs) -> Any: ...

    @property
    def DoubleBuffered(self): ...

    @DoubleBuffered.setter
    def DoubleBuffered(self, value): ...

    def DoubleClick(self, *args, **kwargs) -> Any: ...
    def DpiChanged(self, *args, **kwargs) -> Any: ...
    def DpiChangedAfterParent(self, *args, **kwargs) -> Any: ...
    def DpiChangedBeforeParent(self, *args, **kwargs) -> Any: ...
    def DragDrop(self, *args, **kwargs) -> Any: ...
    def DragEnter(self, *args, **kwargs) -> Any: ...
    def DragLeave(self, *args, **kwargs) -> Any: ...
    def DragOver(self, *args, **kwargs) -> Any: ...

    def DrawToBitmap(
            self,
            _: System.Drawing.Bitmap,
            __: System.Drawing.Rectangle,
            ) -> None: ...

    @property
    def Enabled(self): ...

    @Enabled.setter
    def Enabled(self, value): ...

    def EnabledChanged(self, *args, **kwargs) -> Any: ...
    def EndInvoke(self, _: Any) -> object: ...
    def Enter(self, *args, **kwargs) -> Any: ...
    def Equals(self, _: object, __: object) -> bool: ...

    @property
    def Events(self): ...

    @Events.setter
    def Events(self, value): ...

    def Finalize(self) -> None: ...
    def FindForm(self) -> System.Windows.Forms.Form: ...
    def Focus(self) -> bool: ...

    @property
    def Focused(self): ...

    @Focused.setter
    def Focused(self, value): ...

    @property
    def Font(self): ...

    @Font.setter
    def Font(self, value): ...

    def FontChanged(self, *args, **kwargs) -> Any: ...

    @property
    def FontHeight(self): ...

    @FontHeight.setter
    def FontHeight(self, value): ...

    @property
    def ForeColor(self): ...

    @ForeColor.setter
    def ForeColor(self, value): ...

    def ForeColorChanged(self, *args, **kwargs) -> Any: ...

    @property
    def FormBorderStyle(self): ...

    @FormBorderStyle.setter
    def FormBorderStyle(self, value): ...

    def FormClosed(self, *args, **kwargs) -> Any: ...
    def FormClosing(self, *args, **kwargs) -> Any: ...
    def FromChildHandle(self, _: Any) -> System.Windows.Forms.Control: ...
    def FromHandle(self, _: Any) -> System.Windows.Forms.Control: ...

    def GetAccessibilityObjectById(
            self,
            _: int,
            ) -> System.Windows.Forms.AccessibleObject: ...

    def GetAutoScaleSize(self, _: System.Drawing.Font) -> System.Drawing.SizeF: ...
    def GetAutoSizeMode(self) -> System.Windows.Forms.AutoSizeMode: ...

    def GetChildAtPoint(
            self,
            _: System.Drawing.Point,
            __: System.Windows.Forms.GetChildAtPointSkip,
            ) -> System.Windows.Forms.Control: ...

    def GetContainerControl(self) -> System.Windows.Forms.IContainerControl: ...
    def GetHashCode(self) -> int: ...
    def GetLifetimeService(self) -> object: ...

    def GetNextControl(
            self,
            _: System.Windows.Forms.Control,
            __: bool,
            ) -> System.Windows.Forms.Control: ...

    def GetPreferredSize(self, _: System.Drawing.Size) -> System.Drawing.Size: ...

    def GetScaledBounds(
            self,
            _: System.Drawing.Rectangle,
            __: System.Drawing.SizeF,
            ___: System.Windows.Forms.BoundsSpecified,
            ) -> System.Drawing.Rectangle: ...

    def GetScrollState(self, _: int) -> bool: ...
    def GetService(self, _: Type) -> object: ...
    def GetStyle(self, _: System.Windows.Forms.ControlStyles) -> bool: ...
    def GetTopLevel(self) -> bool: ...
    def GetType(self) -> Type: ...
    def GiveFeedback(self, *args, **kwargs) -> Any: ...
    def GotFocus(self, *args, **kwargs) -> Any: ...

    @property
    def HScroll(self): ...

    @HScroll.setter
    def HScroll(self, value): ...

    @property
    def Handle(self): ...

    @Handle.setter
    def Handle(self, value): ...

    def HandleCreated(self, *args, **kwargs) -> Any: ...
    def HandleDestroyed(self, *args, **kwargs) -> Any: ...

    @property
    def HasChildren(self): ...

    @HasChildren.setter
    def HasChildren(self, value): ...

    @property
    def Height(self): ...

    @Height.setter
    def Height(self, value): ...

    @property
    def HelpButton(self): ...

    @HelpButton.setter
    def HelpButton(self, value): ...

    def HelpButtonClicked(self, *args, **kwargs) -> Any: ...
    def HelpRequested(self, *args, **kwargs) -> Any: ...
    def Hide(self) -> None: ...

    @property
    def HorizontalScroll(self): ...

    @HorizontalScroll.setter
    def HorizontalScroll(self, value): ...

    @property
    def Icon(self): ...

    @Icon.setter
    def Icon(self, value): ...

    @property
    def ImeMode(self): ...

    @ImeMode.setter
    def ImeMode(self, value): ...

    @property
    def ImeModeBase(self): ...

    @ImeModeBase.setter
    def ImeModeBase(self, value): ...

    def ImeModeChanged(self, *args, **kwargs) -> Any: ...
    def InitLayout(self) -> None: ...
    def InitializeLifetimeService(self) -> object: ...
    def InputLanguageChanged(self, *args, **kwargs) -> Any: ...
    def InputLanguageChanging(self, *args, **kwargs) -> Any: ...
    def Invalidate(self, _: System.Drawing.Region, __: bool) -> None: ...
    def Invalidated(self, *args, **kwargs) -> Any: ...
    def Invoke(self, _: Any, __: List[object]) -> object: ...

    def InvokeGotFocus(
            self,
            _: System.Windows.Forms.Control,
            __: System.EventArgs,
            ) -> None: ...

    def InvokeLostFocus(
            self,
            _: System.Windows.Forms.Control,
            __: System.EventArgs,
            ) -> None: ...

    def InvokeOnClick(
            self,
            _: System.Windows.Forms.Control,
            __: System.EventArgs,
            ) -> None: ...

    def InvokePaint(
            self,
            _: System.Windows.Forms.Control,
            __: System.Windows.Forms.PaintEventArgs,
            ) -> None: ...

    def InvokePaintBackground(
            self,
            _: System.Windows.Forms.Control,
            __: System.Windows.Forms.PaintEventArgs,
            ) -> None: ...

    @property
    def InvokeRequired(self): ...

    @InvokeRequired.setter
    def InvokeRequired(self, value): ...

    @property
    def IsAccessible(self): ...

    @IsAccessible.setter
    def IsAccessible(self, value): ...

    @property
    def IsDisposed(self): ...

    @IsDisposed.setter
    def IsDisposed(self, value): ...

    @property
    def IsHandleCreated(self): ...

    @IsHandleCreated.setter
    def IsHandleCreated(self, value): ...

    def IsInputChar(self, _: str) -> bool: ...
    def IsInputKey(self, _: System.Windows.Forms.Keys) -> bool: ...
    def IsKeyLocked(self, _: System.Windows.Forms.Keys) -> bool: ...

    @property
    def IsMdiChild(self): ...

    @IsMdiChild.setter
    def IsMdiChild(self, value): ...

    @property
    def IsMdiContainer(self): ...

    @IsMdiContainer.setter
    def IsMdiContainer(self, value): ...

    @property
    def IsMirrored(self): ...

    @IsMirrored.setter
    def IsMirrored(self, value): ...

    def IsMnemonic(self, _: str, __: str) -> bool: ...

    @property
    def IsRestrictedWindow(self): ...

    @IsRestrictedWindow.setter
    def IsRestrictedWindow(self, value): ...

    def KeyDown(self, *args, **kwargs) -> Any: ...
    def KeyPress(self, *args, **kwargs) -> Any: ...

    @property
    def KeyPreview(self): ...

    @KeyPreview.setter
    def KeyPreview(self, value): ...

    def KeyUp(self, *args, **kwargs) -> Any: ...
    def Layout(self, *args, **kwargs) -> Any: ...

    @property
    def LayoutEngine(self): ...

    @LayoutEngine.setter
    def LayoutEngine(self, value): ...

    def LayoutMdi(self, _: System.Windows.Forms.MdiLayout) -> None: ...
    def Leave(self, *args, **kwargs) -> Any: ...

    @property
    def Left(self): ...

    @Left.setter
    def Left(self, value): ...

    def Load(self, *args, **kwargs) -> Any: ...

    @property
    def Location(self): ...

    @Location.setter
    def Location(self, value): ...

    def LocationChanged(self, *args, **kwargs) -> Any: ...
    def LogicalToDeviceUnits(self, _: int) -> int: ...
    def LostFocus(self, *args, **kwargs) -> Any: ...

    @property
    def MainMenuStrip(self): ...

    @MainMenuStrip.setter
    def MainMenuStrip(self, value): ...

    @property
    def Margin(self): ...

    @Margin.setter
    def Margin(self, value): ...

    def MarginChanged(self, *args, **kwargs) -> Any: ...

    @property
    def MaximizeBox(self): ...

    @MaximizeBox.setter
    def MaximizeBox(self, value): ...

    @property
    def MaximizedBounds(self): ...

    @MaximizedBounds.setter
    def MaximizedBounds(self, value): ...

    def MaximizedBoundsChanged(self, *args, **kwargs) -> Any: ...

    @property
    def MaximumSize(self): ...

    @MaximumSize.setter
    def MaximumSize(self, value): ...

    def MaximumSizeChanged(self, *args, **kwargs) -> Any: ...
    def MdiChildActivate(self, *args, **kwargs) -> Any: ...

    @property
    def MdiChildren(self): ...

    @MdiChildren.setter
    def MdiChildren(self, value): ...

    @property
    def MdiParent(self): ...

    @MdiParent.setter
    def MdiParent(self, value): ...

    def MemberwiseClone(self) -> object: ...

    @property
    def Menu(self): ...

    @Menu.setter
    def Menu(self, value): ...

    def MenuComplete(self, *args, **kwargs) -> Any: ...
    def MenuStart(self, *args, **kwargs) -> Any: ...

    @property
    def MergedMenu(self): ...

    @MergedMenu.setter
    def MergedMenu(self, value): ...

    @property
    def MinimizeBox(self): ...

    @MinimizeBox.setter
    def MinimizeBox(self, value): ...

    @property
    def MinimumSize(self): ...

    @MinimumSize.setter
    def MinimumSize(self, value): ...

    def MinimumSizeChanged(self, *args, **kwargs) -> Any: ...

    @property
    def Modal(self): ...

    @Modal.setter
    def Modal(self, value): ...

    def ModifierKeys(self, *args, **kwargs) -> Any: ...
    def MouseButtons(self, *args, **kwargs) -> Any: ...
    def MouseCaptureChanged(self, *args, **kwargs) -> Any: ...
    def MouseClick(self, *args, **kwargs) -> Any: ...
    def MouseDoubleClick(self, *args, **kwargs) -> Any: ...
    def MouseDown(self, *args, **kwargs) -> Any: ...
    def MouseEnter(self, *args, **kwargs) -> Any: ...
    def MouseHover(self, *args, **kwargs) -> Any: ...
    def MouseLeave(self, *args, **kwargs) -> Any: ...
    def MouseMove(self, *args, **kwargs) -> Any: ...
    def MousePosition(self, *args, **kwargs) -> Any: ...
    def MouseUp(self, *args, **kwargs) -> Any: ...
    def MouseWheel(self, *args, **kwargs) -> Any: ...
    def Move(self, *args, **kwargs) -> Any: ...

    @property
    def Name(self): ...

    @Name.setter
    def Name(self, value): ...

    def NotifyInvalidate(self, _: System.Drawing.Rectangle) -> None: ...
    def OnActivated(self, _: System.EventArgs) -> None: ...
    def OnAutoSizeChanged(self, _: System.EventArgs) -> None: ...
    def OnAutoValidateChanged(self, _: System.EventArgs) -> None: ...
    def OnBackColorChanged(self, _: System.EventArgs) -> None: ...
    def OnBackgroundImageChanged(self, _: System.EventArgs) -> None: ...
    def OnBackgroundImageLayoutChanged(self, _: System.EventArgs) -> None: ...
    def OnBindingContextChanged(self, _: System.EventArgs) -> None: ...
    def OnCausesValidationChanged(self, _: System.EventArgs) -> None: ...
    def OnChangeUICues(self, _: System.Windows.Forms.UICuesEventArgs) -> None: ...
    def OnClick(self, _: System.EventArgs) -> None: ...
    def OnClientSizeChanged(self, _: System.EventArgs) -> None: ...
    def OnClosed(self, _: System.EventArgs) -> None: ...
    def OnClosing(self, _: System.ComponentModel.CancelEventArgs) -> None: ...
    def OnContextMenuChanged(self, _: System.EventArgs) -> None: ...
    def OnContextMenuStripChanged(self, _: System.EventArgs) -> None: ...
    def OnControlAdded(self, _: System.Windows.Forms.ControlEventArgs) -> None: ...
    def OnControlRemoved(self, _: System.Windows.Forms.ControlEventArgs) -> None: ...
    def OnCreateControl(self) -> None: ...
    def OnCursorChanged(self, _: System.EventArgs) -> None: ...
    def OnDeactivate(self, _: System.EventArgs) -> None: ...
    def OnDockChanged(self, _: System.EventArgs) -> None: ...
    def OnDoubleClick(self, _: System.EventArgs) -> None: ...
    def OnDpiChanged(self, _: System.Windows.Forms.DpiChangedEventArgs) -> None: ...
    def OnDpiChangedAfterParent(self, _: System.EventArgs) -> None: ...
    def OnDpiChangedBeforeParent(self, _: System.EventArgs) -> None: ...
    def OnDragDrop(self, _: System.Windows.Forms.DragEventArgs) -> None: ...
    def OnDragEnter(self, _: System.Windows.Forms.DragEventArgs) -> None: ...
    def OnDragLeave(self, _: System.EventArgs) -> None: ...
    def OnDragOver(self, _: System.Windows.Forms.DragEventArgs) -> None: ...
    def OnEnabledChanged(self, _: System.EventArgs) -> None: ...
    def OnEnter(self, _: System.EventArgs) -> None: ...
    def OnFontChanged(self, _: System.EventArgs) -> None: ...
    def OnForeColorChanged(self, _: System.EventArgs) -> None: ...
    def OnFormClosed(self, _: System.Windows.Forms.FormClosedEventArgs) -> None: ...
    def OnFormClosing(self, _: System.Windows.Forms.FormClosingEventArgs) -> None: ...
    def OnGetDpiScaledSize(self, _: int, __: int, ___: System.Drawing.Size) -> bool: ...
    def OnGiveFeedback(self, _: System.Windows.Forms.GiveFeedbackEventArgs) -> None: ...
    def OnGotFocus(self, _: System.EventArgs) -> None: ...
    def OnHandleCreated(self, _: System.EventArgs) -> None: ...
    def OnHandleDestroyed(self, _: System.EventArgs) -> None: ...
    def OnHelpButtonClicked(self, _: System.ComponentModel.CancelEventArgs) -> None: ...
    def OnHelpRequested(self, _: System.Windows.Forms.HelpEventArgs) -> None: ...
    def OnImeModeChanged(self, _: System.EventArgs) -> None: ...

    def OnInputLanguageChanged(
            self,
            _: System.Windows.Forms.InputLanguageChangedEventArgs,
            ) -> None: ...

    def OnInputLanguageChanging(
            self,
            _: System.Windows.Forms.InputLanguageChangingEventArgs,
            ) -> None: ...

    def OnInvalidated(self, _: System.Windows.Forms.InvalidateEventArgs) -> None: ...
    def OnKeyDown(self, _: System.Windows.Forms.KeyEventArgs) -> None: ...
    def OnKeyPress(self, _: System.Windows.Forms.KeyPressEventArgs) -> None: ...
    def OnKeyUp(self, _: System.Windows.Forms.KeyEventArgs) -> None: ...
    def OnLayout(self, _: System.Windows.Forms.LayoutEventArgs) -> None: ...
    def OnLeave(self, _: System.EventArgs) -> None: ...
    def OnLoad(self, _: System.EventArgs) -> None: ...
    def OnLocationChanged(self, _: System.EventArgs) -> None: ...
    def OnLostFocus(self, _: System.EventArgs) -> None: ...
    def OnMarginChanged(self, _: System.EventArgs) -> None: ...
    def OnMaximizedBoundsChanged(self, _: System.EventArgs) -> None: ...
    def OnMaximumSizeChanged(self, _: System.EventArgs) -> None: ...
    def OnMdiChildActivate(self, _: System.EventArgs) -> None: ...
    def OnMenuComplete(self, _: System.EventArgs) -> None: ...
    def OnMenuStart(self, _: System.EventArgs) -> None: ...
    def OnMinimumSizeChanged(self, _: System.EventArgs) -> None: ...
    def OnMouseCaptureChanged(self, _: System.EventArgs) -> None: ...
    def OnMouseClick(self, _: System.Windows.Forms.MouseEventArgs) -> None: ...
    def OnMouseDoubleClick(self, _: System.Windows.Forms.MouseEventArgs) -> None: ...
    def OnMouseDown(self, _: System.Windows.Forms.MouseEventArgs) -> None: ...
    def OnMouseEnter(self, _: System.EventArgs) -> None: ...
    def OnMouseHover(self, _: System.EventArgs) -> None: ...
    def OnMouseLeave(self, _: System.EventArgs) -> None: ...
    def OnMouseMove(self, _: System.Windows.Forms.MouseEventArgs) -> None: ...
    def OnMouseUp(self, _: System.Windows.Forms.MouseEventArgs) -> None: ...
    def OnMouseWheel(self, _: System.Windows.Forms.MouseEventArgs) -> None: ...
    def OnMove(self, _: System.EventArgs) -> None: ...
    def OnNotifyMessage(self, _: System.Windows.Forms.Message) -> None: ...
    def OnPaddingChanged(self, _: System.EventArgs) -> None: ...
    def OnPaint(self, _: System.Windows.Forms.PaintEventArgs) -> None: ...
    def OnPaintBackground(self, _: System.Windows.Forms.PaintEventArgs) -> None: ...
    def OnParentBackColorChanged(self, _: System.EventArgs) -> None: ...
    def OnParentBackgroundImageChanged(self, _: System.EventArgs) -> None: ...
    def OnParentBindingContextChanged(self, _: System.EventArgs) -> None: ...
    def OnParentChanged(self, _: System.EventArgs) -> None: ...
    def OnParentCursorChanged(self, _: System.EventArgs) -> None: ...
    def OnParentEnabledChanged(self, _: System.EventArgs) -> None: ...
    def OnParentFontChanged(self, _: System.EventArgs) -> None: ...
    def OnParentForeColorChanged(self, _: System.EventArgs) -> None: ...
    def OnParentRightToLeftChanged(self, _: System.EventArgs) -> None: ...
    def OnParentVisibleChanged(self, _: System.EventArgs) -> None: ...
    def OnPreviewKeyDown(self, _: System.Windows.Forms.PreviewKeyDownEventArgs) -> None: ...
    def OnPrint(self, _: System.Windows.Forms.PaintEventArgs) -> None: ...

    def OnQueryContinueDrag(
            self,
            _: System.Windows.Forms.QueryContinueDragEventArgs,
            ) -> None: ...

    def OnRegionChanged(self, _: System.EventArgs) -> None: ...
    def OnResize(self, _: System.EventArgs) -> None: ...
    def OnResizeBegin(self, _: System.EventArgs) -> None: ...
    def OnResizeEnd(self, _: System.EventArgs) -> None: ...
    def OnRightToLeftChanged(self, _: System.EventArgs) -> None: ...
    def OnRightToLeftLayoutChanged(self, _: System.EventArgs) -> None: ...
    def OnScroll(self, _: System.Windows.Forms.ScrollEventArgs) -> None: ...
    def OnShown(self, _: System.EventArgs) -> None: ...
    def OnSizeChanged(self, _: System.EventArgs) -> None: ...
    def OnStyleChanged(self, _: System.EventArgs) -> None: ...
    def OnSystemColorsChanged(self, _: System.EventArgs) -> None: ...
    def OnTabIndexChanged(self, _: System.EventArgs) -> None: ...
    def OnTabStopChanged(self, _: System.EventArgs) -> None: ...
    def OnTextChanged(self, _: System.EventArgs) -> None: ...
    def OnValidated(self, _: System.EventArgs) -> None: ...
    def OnValidating(self, _: System.ComponentModel.CancelEventArgs) -> None: ...
    def OnVisibleChanged(self, _: System.EventArgs) -> None: ...

    @property
    def Opacity(self): ...

    @Opacity.setter
    def Opacity(self, value): ...

    def Overloads(self, *args, **kwargs) -> Any: ...

    @property
    def OwnedForms(self): ...

    @OwnedForms.setter
    def OwnedForms(self, value): ...

    @property
    def Owner(self): ...

    @Owner.setter
    def Owner(self, value): ...

    @property
    def Padding(self): ...

    @Padding.setter
    def Padding(self, value): ...

    def PaddingChanged(self, *args, **kwargs) -> Any: ...
    def Paint(self, *args, **kwargs) -> Any: ...

    @property
    def Parent(self): ...

    @Parent.setter
    def Parent(self, value): ...

    def ParentChanged(self, *args, **kwargs) -> Any: ...

    @property
    def ParentForm(self): ...

    @ParentForm.setter
    def ParentForm(self, value): ...

    def PerformAutoScale(self) -> None: ...
    def PerformLayout(self, _: System.Windows.Forms.Control, __: str) -> None: ...
    def PointToClient(self, _: System.Drawing.Point) -> System.Drawing.Point: ...
    def PointToScreen(self, _: System.Drawing.Point) -> System.Drawing.Point: ...

    def PreProcessControlMessage(
            self,
            _: System.Windows.Forms.Message,
            ) -> System.Windows.Forms.PreProcessControlState: ...

    def PreProcessMessage(self, _: System.Windows.Forms.Message) -> bool: ...

    @property
    def PreferredSize(self): ...

    @PreferredSize.setter
    def PreferredSize(self, value): ...

    def PreviewKeyDown(self, *args, **kwargs) -> Any: ...

    def ProcessCmdKey(
            self,
            _: System.Windows.Forms.Message,
            __: System.Windows.Forms.Keys,
            ) -> bool: ...

    def ProcessDialogChar(self, _: str) -> bool: ...
    def ProcessDialogKey(self, _: System.Windows.Forms.Keys) -> bool: ...
    def ProcessKeyEventArgs(self, _: System.Windows.Forms.Message) -> bool: ...
    def ProcessKeyMessage(self, _: System.Windows.Forms.Message) -> bool: ...
    def ProcessKeyPreview(self, _: System.Windows.Forms.Message) -> bool: ...
    def ProcessMnemonic(self, _: str) -> bool: ...
    def ProcessTabKey(self, _: bool) -> bool: ...

    @property
    def ProductName(self): ...

    @ProductName.setter
    def ProductName(self, value): ...

    @property
    def ProductVersion(self): ...

    @ProductVersion.setter
    def ProductVersion(self, value): ...

    def PropagatingImeMode(self, *args, **kwargs) -> Any: ...
    def QueryAccessibilityHelp(self, *args, **kwargs) -> Any: ...
    def QueryContinueDrag(self, *args, **kwargs) -> Any: ...
    def RaiseDragEvent(self, _: object, __: System.Windows.Forms.DragEventArgs) -> None: ...
    def RaiseKeyEvent(self, _: object, __: System.Windows.Forms.KeyEventArgs) -> None: ...

    def RaiseMouseEvent(
            self,
            _: object,
            __: System.Windows.Forms.MouseEventArgs,
            ) -> None: ...

    def RaisePaintEvent(
            self,
            _: object,
            __: System.Windows.Forms.PaintEventArgs,
            ) -> None: ...

    def RecreateHandle(self) -> None: ...

    @property
    def RecreatingHandle(self): ...

    @RecreatingHandle.setter
    def RecreatingHandle(self, value): ...

    def RectangleToClient(
            self,
            _: System.Drawing.Rectangle,
            ) -> System.Drawing.Rectangle: ...

    def RectangleToScreen(
            self,
            _: System.Drawing.Rectangle,
            ) -> System.Drawing.Rectangle: ...

    def ReferenceEquals(self, _: object, __: object) -> bool: ...
    def ReflectMessage(self, _: Any, __: System.Windows.Forms.Message) -> bool: ...
    def Refresh(self) -> None: ...

    @property
    def Region(self): ...

    @Region.setter
    def Region(self, value): ...

    def RegionChanged(self, *args, **kwargs) -> Any: ...
    def RemoveOwnedForm(self, _: System.Windows.Forms.Form) -> None: ...

    @property
    def RenderRightToLeft(self): ...

    @RenderRightToLeft.setter
    def RenderRightToLeft(self, value): ...

    def RescaleConstantsForDpi(self, _: int, __: int) -> None: ...
    def ResetBackColor(self) -> None: ...
    def ResetBindings(self) -> None: ...
    def ResetCursor(self) -> None: ...
    def ResetFont(self) -> None: ...
    def ResetForeColor(self) -> None: ...
    def ResetImeMode(self) -> None: ...
    def ResetMouseEventArgs(self) -> None: ...
    def ResetRightToLeft(self) -> None: ...
    def ResetText(self) -> None: ...
    def Resize(self, *args, **kwargs) -> Any: ...
    def ResizeBegin(self, *args, **kwargs) -> Any: ...
    def ResizeEnd(self, *args, **kwargs) -> Any: ...

    @property
    def ResizeRedraw(self): ...

    @ResizeRedraw.setter
    def ResizeRedraw(self, value): ...

    @property
    def RestoreBounds(self): ...

    @RestoreBounds.setter
    def RestoreBounds(self, value): ...

    def ResumeLayout(self, _: bool) -> None: ...

    @property
    def Right(self): ...

    @Right.setter
    def Right(self, value): ...

    @property
    def RightToLeft(self): ...

    @RightToLeft.setter
    def RightToLeft(self, value): ...

    def RightToLeftChanged(self, *args, **kwargs) -> Any: ...

    @property
    def RightToLeftLayout(self): ...

    @RightToLeftLayout.setter
    def RightToLeftLayout(self, value): ...

    def RightToLeftLayoutChanged(self, *args, **kwargs) -> Any: ...

    def RtlTranslateAlignment(
            self,
            _: System.Windows.Forms.HorizontalAlignment,
            ) -> System.Windows.Forms.HorizontalAlignment: ...

    def RtlTranslateContent(
            self,
            _: System.Drawing.ContentAlignment,
            ) -> System.Drawing.ContentAlignment: ...

    def RtlTranslateHorizontal(
            self,
            _: System.Windows.Forms.HorizontalAlignment,
            ) -> System.Windows.Forms.HorizontalAlignment: ...

    def RtlTranslateLeftRight(
            self,
            _: System.Windows.Forms.LeftRightAlignment,
            ) -> System.Windows.Forms.LeftRightAlignment: ...

    def Scale(self, _: float, __: float) -> None: ...
    def ScaleBitmapLogicalToDevice(self, _: System.Drawing.Bitmap) -> None: ...

    @property
    def ScaleChildren(self): ...

    @ScaleChildren.setter
    def ScaleChildren(self, value): ...

    def ScaleControl(
            self,
            _: System.Drawing.SizeF,
            __: System.Windows.Forms.BoundsSpecified,
            ) -> None: ...

    def ScaleCore(self, _: float, __: float) -> None: ...
    def Scroll(self, *args, **kwargs) -> Any: ...
    def ScrollControlIntoView(self, _: System.Windows.Forms.Control) -> None: ...
    def ScrollStateAutoScrolling(self, *args, **kwargs) -> Any: ...
    def ScrollStateFullDrag(self, *args, **kwargs) -> Any: ...
    def ScrollStateHScrollVisible(self, *args, **kwargs) -> Any: ...
    def ScrollStateUserHasScrolled(self, *args, **kwargs) -> Any: ...
    def ScrollStateVScrollVisible(self, *args, **kwargs) -> Any: ...
    def ScrollToControl(self, _: System.Windows.Forms.Control) -> System.Drawing.Point: ...
    def Select(self) -> None: ...

    def SelectNextControl(
            self,
            _: System.Windows.Forms.Control,
            __: bool,
            ___: bool,
            ____: bool,
            _____: bool,
            ) -> bool: ...

    def SendToBack(self) -> None: ...
    def SetAutoScrollMargin(self, _: int, __: int) -> None: ...
    def SetAutoSizeMode(self, _: System.Windows.Forms.AutoSizeMode) -> None: ...

    def SetBounds(
            self,
            _: int,
            __: int,
            ___: int,
            ____: int,
            _____: System.Windows.Forms.BoundsSpecified,
            ) -> None: ...

    def SetBoundsCore(
            self,
            _: int,
            __: int,
            ___: int,
            ____: int,
            _____: System.Windows.Forms.BoundsSpecified,
            ) -> None: ...

    def SetClientSizeCore(self, _: int, __: int) -> None: ...
    def SetDesktopBounds(self, _: int, __: int, ___: int, ____: int) -> None: ...
    def SetDesktopLocation(self, _: int, __: int) -> None: ...
    def SetDisplayRectLocation(self, _: int, __: int) -> None: ...
    def SetScrollState(self, _: int, __: bool) -> None: ...
    def SetStyle(self, _: System.Windows.Forms.ControlStyles, __: bool) -> None: ...
    def SetTopLevel(self, _: bool) -> None: ...
    def SetVisibleCore(self, _: bool) -> None: ...
    def Show(self) -> None: ...

    def ShowDialog(
            self,
            _: System.Windows.Forms.IWin32Window,
            ) -> System.Windows.Forms.DialogResult: ...

    @property
    def ShowFocusCues(self): ...

    @ShowFocusCues.setter
    def ShowFocusCues(self, value): ...

    @property
    def ShowIcon(self): ...

    @ShowIcon.setter
    def ShowIcon(self, value): ...

    @property
    def ShowInTaskbar(self): ...

    @ShowInTaskbar.setter
    def ShowInTaskbar(self, value): ...

    @property
    def ShowKeyboardCues(self): ...

    @ShowKeyboardCues.setter
    def ShowKeyboardCues(self, value): ...

    @property
    def ShowWithoutActivation(self): ...

    @ShowWithoutActivation.setter
    def ShowWithoutActivation(self, value): ...

    def Shown(self, *args, **kwargs) -> Any: ...

    @property
    def Site(self): ...

    @Site.setter
    def Site(self, value): ...

    @property
    def Size(self): ...

    @Size.setter
    def Size(self, value): ...

    def SizeChanged(self, *args, **kwargs) -> Any: ...
    def SizeFromClientSize(self, _: System.Drawing.Size) -> System.Drawing.Size: ...

    @property
    def SizeGripStyle(self): ...

    @SizeGripStyle.setter
    def SizeGripStyle(self, value): ...

    @property
    def StartPosition(self): ...

    @StartPosition.setter
    def StartPosition(self, value): ...

    def StyleChanged(self, *args, **kwargs) -> Any: ...
    def SuspendLayout(self) -> None: ...
    def SystemColorsChanged(self, *args, **kwargs) -> Any: ...

    @property
    def TabIndex(self): ...

    @TabIndex.setter
    def TabIndex(self, value): ...

    def TabIndexChanged(self, *args, **kwargs) -> Any: ...

    @property
    def TabStop(self): ...

    @TabStop.setter
    def TabStop(self, value): ...

    def TabStopChanged(self, *args, **kwargs) -> Any: ...

    @property
    def Tag(self): ...

    @Tag.setter
    def Tag(self, value): ...

    @property
    def Text(self): ...

    @Text.setter
    def Text(self, value): ...

    def TextChanged(self, *args, **kwargs) -> Any: ...
    def ToString(self) -> str: ...

    @property
    def Top(self): ...

    @Top.setter
    def Top(self, value): ...

    @property
    def TopLevel(self): ...

    @TopLevel.setter
    def TopLevel(self, value): ...

    @property
    def TopLevelControl(self): ...

    @TopLevelControl.setter
    def TopLevelControl(self, value): ...

    @property
    def TopMost(self): ...

    @TopMost.setter
    def TopMost(self, value): ...

    @property
    def TransparencyKey(self): ...

    @TransparencyKey.setter
    def TransparencyKey(self, value): ...

    def Update(self) -> None: ...

    def UpdateBounds(
            self,
            _: int,
            __: int,
            ___: int,
            ____: int,
            _____: int,
            ______: int,
            ) -> None: ...

    def UpdateDefaultButton(self) -> None: ...
    def UpdateStyles(self) -> None: ...
    def UpdateZOrder(self) -> None: ...

    @property
    def UseWaitCursor(self): ...

    @UseWaitCursor.setter
    def UseWaitCursor(self, value): ...

    @property
    def VScroll(self): ...

    @VScroll.setter
    def VScroll(self, value): ...

    def Validate(self, _: bool) -> bool: ...
    def ValidateChildren(self, _: System.Windows.Forms.ValidationConstraints) -> bool: ...
    def Validated(self, *args, **kwargs) -> Any: ...
    def Validating(self, *args, **kwargs) -> Any: ...

    @property
    def VerticalScroll(self): ...

    @VerticalScroll.setter
    def VerticalScroll(self, value): ...

    @property
    def Visible(self): ...

    @Visible.setter
    def Visible(self, value): ...

    def VisibleChanged(self, *args, **kwargs) -> Any: ...

    @property
    def Width(self): ...

    @Width.setter
    def Width(self, value): ...

    @property
    def WindowState(self): ...

    @WindowState.setter
    def WindowState(self, value): ...

    @property
    def WindowTarget(self): ...

    @WindowTarget.setter
    def WindowTarget(self, value): ...

    def WndProc(self, _: System.Windows.Forms.Message) -> None: ...
    def add_Activated(self, _: Any) -> None: ...
    def add_AutoSizeChanged(self, _: Any) -> None: ...
    def add_AutoValidateChanged(self, _: Any) -> None: ...
    def add_BackColorChanged(self, _: Any) -> None: ...
    def add_BackgroundImageChanged(self, _: Any) -> None: ...
    def add_BackgroundImageLayoutChanged(self, _: Any) -> None: ...
    def add_BindingContextChanged(self, _: Any) -> None: ...
    def add_CausesValidationChanged(self, _: Any) -> None: ...
    def add_ChangeUICues(self, _: System.Windows.Forms.UICuesEventHandler) -> None: ...
    def add_Click(self, _: Any) -> None: ...
    def add_ClientSizeChanged(self, _: Any) -> None: ...
    def add_Closed(self, _: Any) -> None: ...
    def add_Closing(self, _: System.ComponentModel.CancelEventHandler) -> None: ...
    def add_ContextMenuChanged(self, _: Any) -> None: ...
    def add_ContextMenuStripChanged(self, _: Any) -> None: ...
    def add_ControlAdded(self, _: System.Windows.Forms.ControlEventHandler) -> None: ...
    def add_ControlRemoved(self, _: System.Windows.Forms.ControlEventHandler) -> None: ...
    def add_CursorChanged(self, _: Any) -> None: ...
    def add_Deactivate(self, _: Any) -> None: ...
    def add_Disposed(self, _: Any) -> None: ...
    def add_DockChanged(self, _: Any) -> None: ...
    def add_DoubleClick(self, _: Any) -> None: ...
    def add_DpiChanged(self, _: System.Windows.Forms.DpiChangedEventHandler) -> None: ...
    def add_DpiChangedAfterParent(self, _: Any) -> None: ...
    def add_DpiChangedBeforeParent(self, _: Any) -> None: ...
    def add_DragDrop(self, _: System.Windows.Forms.DragEventHandler) -> None: ...
    def add_DragEnter(self, _: System.Windows.Forms.DragEventHandler) -> None: ...
    def add_DragLeave(self, _: Any) -> None: ...
    def add_DragOver(self, _: System.Windows.Forms.DragEventHandler) -> None: ...
    def add_EnabledChanged(self, _: Any) -> None: ...
    def add_Enter(self, _: Any) -> None: ...
    def add_FontChanged(self, _: Any) -> None: ...
    def add_ForeColorChanged(self, _: Any) -> None: ...
    def add_FormClosed(self, _: System.Windows.Forms.FormClosedEventHandler) -> None: ...
    def add_FormClosing(self, _: System.Windows.Forms.FormClosingEventHandler) -> None: ...

    def add_GiveFeedback(
            self,
            _: System.Windows.Forms.GiveFeedbackEventHandler,
            ) -> None: ...

    def add_GotFocus(self, _: Any) -> None: ...
    def add_HandleCreated(self, _: Any) -> None: ...
    def add_HandleDestroyed(self, _: Any) -> None: ...

    def add_HelpButtonClicked(
            self,
            _: System.ComponentModel.CancelEventHandler,
            ) -> None: ...

    def add_HelpRequested(self, _: System.Windows.Forms.HelpEventHandler) -> None: ...
    def add_ImeModeChanged(self, _: Any) -> None: ...

    def add_InputLanguageChanged(
            self,
            _: System.Windows.Forms.InputLanguageChangedEventHandler,
            ) -> None: ...

    def add_InputLanguageChanging(
            self,
            _: System.Windows.Forms.InputLanguageChangingEventHandler,
            ) -> None: ...

    def add_Invalidated(self, _: System.Windows.Forms.InvalidateEventHandler) -> None: ...
    def add_KeyDown(self, _: System.Windows.Forms.KeyEventHandler) -> None: ...
    def add_KeyPress(self, _: System.Windows.Forms.KeyPressEventHandler) -> None: ...
    def add_KeyUp(self, _: System.Windows.Forms.KeyEventHandler) -> None: ...
    def add_Layout(self, _: System.Windows.Forms.LayoutEventHandler) -> None: ...
    def add_Leave(self, _: Any) -> None: ...
    def add_Load(self, _: Any) -> None: ...
    def add_LocationChanged(self, _: Any) -> None: ...
    def add_LostFocus(self, _: Any) -> None: ...
    def add_MarginChanged(self, _: Any) -> None: ...
    def add_MaximizedBoundsChanged(self, _: Any) -> None: ...
    def add_MaximumSizeChanged(self, _: Any) -> None: ...
    def add_MdiChildActivate(self, _: Any) -> None: ...
    def add_MenuComplete(self, _: Any) -> None: ...
    def add_MenuStart(self, _: Any) -> None: ...
    def add_MinimumSizeChanged(self, _: Any) -> None: ...
    def add_MouseCaptureChanged(self, _: Any) -> None: ...
    def add_MouseClick(self, _: System.Windows.Forms.MouseEventHandler) -> None: ...
    def add_MouseDoubleClick(self, _: System.Windows.Forms.MouseEventHandler) -> None: ...
    def add_MouseDown(self, _: System.Windows.Forms.MouseEventHandler) -> None: ...
    def add_MouseEnter(self, _: Any) -> None: ...
    def add_MouseHover(self, _: Any) -> None: ...
    def add_MouseLeave(self, _: Any) -> None: ...
    def add_MouseMove(self, _: System.Windows.Forms.MouseEventHandler) -> None: ...
    def add_MouseUp(self, _: System.Windows.Forms.MouseEventHandler) -> None: ...
    def add_MouseWheel(self, _: System.Windows.Forms.MouseEventHandler) -> None: ...
    def add_Move(self, _: Any) -> None: ...
    def add_PaddingChanged(self, _: Any) -> None: ...
    def add_Paint(self, _: System.Windows.Forms.PaintEventHandler) -> None: ...
    def add_ParentChanged(self, _: Any) -> None: ...

    def add_PreviewKeyDown(
            self,
            _: System.Windows.Forms.PreviewKeyDownEventHandler,
            ) -> None: ...

    def add_QueryAccessibilityHelp(
            self,
            _: System.Windows.Forms.QueryAccessibilityHelpEventHandler,
            ) -> None: ...

    def add_QueryContinueDrag(
            self,
            _: System.Windows.Forms.QueryContinueDragEventHandler,
            ) -> None: ...

    def add_RegionChanged(self, _: Any) -> None: ...
    def add_Resize(self, _: Any) -> None: ...
    def add_ResizeBegin(self, _: Any) -> None: ...
    def add_ResizeEnd(self, _: Any) -> None: ...
    def add_RightToLeftChanged(self, _: Any) -> None: ...
    def add_RightToLeftLayoutChanged(self, _: Any) -> None: ...
    def add_Scroll(self, _: System.Windows.Forms.ScrollEventHandler) -> None: ...
    def add_Shown(self, _: Any) -> None: ...
    def add_SizeChanged(self, _: Any) -> None: ...
    def add_StyleChanged(self, _: Any) -> None: ...
    def add_SystemColorsChanged(self, _: Any) -> None: ...
    def add_TabIndexChanged(self, _: Any) -> None: ...
    def add_TabStopChanged(self, _: Any) -> None: ...
    def add_TextChanged(self, _: Any) -> None: ...
    def add_Validated(self, _: Any) -> None: ...
    def add_Validating(self, _: System.ComponentModel.CancelEventHandler) -> None: ...
    def add_VisibleChanged(self, _: Any) -> None: ...
    def get_AcceptButton(self) -> System.Windows.Forms.IButtonControl: ...
    def get_AccessibilityObject(self) -> System.Windows.Forms.AccessibleObject: ...
    def get_AccessibleDefaultActionDescription(self) -> str: ...
    def get_AccessibleDescription(self) -> str: ...
    def get_AccessibleName(self) -> str: ...
    def get_AccessibleRole(self) -> System.Windows.Forms.AccessibleRole: ...
    def get_ActiveControl(self) -> System.Windows.Forms.Control: ...
    def get_ActiveForm(self) -> System.Windows.Forms.Form: ...
    def get_ActiveMdiChild(self) -> System.Windows.Forms.Form: ...
    def get_AllowDrop(self) -> bool: ...
    def get_AllowTransparency(self) -> bool: ...
    def get_Anchor(self) -> System.Windows.Forms.AnchorStyles: ...
    def get_AutoScale(self) -> bool: ...
    def get_AutoScaleBaseSize(self) -> System.Drawing.Size: ...
    def get_AutoScaleDimensions(self) -> System.Drawing.SizeF: ...
    def get_AutoScaleFactor(self) -> System.Drawing.SizeF: ...
    def get_AutoScaleMode(self) -> System.Windows.Forms.AutoScaleMode: ...
    def get_AutoScroll(self) -> bool: ...
    def get_AutoScrollMargin(self) -> System.Drawing.Size: ...
    def get_AutoScrollMinSize(self) -> System.Drawing.Size: ...
    def get_AutoScrollOffset(self) -> System.Drawing.Point: ...
    def get_AutoScrollPosition(self) -> System.Drawing.Point: ...
    def get_AutoSize(self) -> bool: ...
    def get_AutoSizeMode(self) -> System.Windows.Forms.AutoSizeMode: ...
    def get_AutoValidate(self) -> System.Windows.Forms.AutoValidate: ...
    def get_BackColor(self) -> System.Drawing.Color: ...
    def get_BackgroundImage(self) -> System.Drawing.Image: ...
    def get_BackgroundImageLayout(self) -> System.Windows.Forms.ImageLayout: ...
    def get_BindingContext(self) -> System.Windows.Forms.BindingContext: ...
    def get_Bottom(self) -> int: ...
    def get_Bounds(self) -> System.Drawing.Rectangle: ...
    def get_CanEnableIme(self) -> bool: ...
    def get_CanFocus(self) -> bool: ...
    def get_CanRaiseEvents(self) -> bool: ...
    def get_CanSelect(self) -> bool: ...
    def get_CancelButton(self) -> System.Windows.Forms.IButtonControl: ...
    def get_Capture(self) -> bool: ...
    def get_CausesValidation(self) -> bool: ...
    def get_CheckForIllegalCrossThreadCalls(self) -> bool: ...
    def get_ClientRectangle(self) -> System.Drawing.Rectangle: ...
    def get_ClientSize(self) -> System.Drawing.Size: ...
    def get_CompanyName(self) -> str: ...
    def get_Container(self) -> System.ComponentModel.IContainer: ...
    def get_ContainsFocus(self) -> bool: ...
    def get_ContextMenu(self) -> System.Windows.Forms.ContextMenu: ...
    def get_ContextMenuStrip(self) -> System.Windows.Forms.ContextMenuStrip: ...
    def get_ControlBox(self) -> bool: ...
    def get_Controls(self) -> Any: ...
    def get_CreateParams(self) -> System.Windows.Forms.CreateParams: ...
    def get_Created(self) -> bool: ...
    def get_CurrentAutoScaleDimensions(self) -> System.Drawing.SizeF: ...
    def get_Cursor(self) -> System.Windows.Forms.Cursor: ...
    def get_DataBindings(self) -> System.Windows.Forms.ControlBindingsCollection: ...
    def get_DefaultBackColor(self) -> System.Drawing.Color: ...
    def get_DefaultCursor(self) -> System.Windows.Forms.Cursor: ...
    def get_DefaultFont(self) -> System.Drawing.Font: ...
    def get_DefaultForeColor(self) -> System.Drawing.Color: ...
    def get_DefaultImeMode(self) -> System.Windows.Forms.ImeMode: ...
    def get_DefaultMargin(self) -> System.Windows.Forms.Padding: ...
    def get_DefaultMaximumSize(self) -> System.Drawing.Size: ...
    def get_DefaultMinimumSize(self) -> System.Drawing.Size: ...
    def get_DefaultPadding(self) -> System.Windows.Forms.Padding: ...
    def get_DefaultSize(self) -> System.Drawing.Size: ...
    def get_DesignMode(self) -> bool: ...
    def get_DesktopBounds(self) -> System.Drawing.Rectangle: ...
    def get_DesktopLocation(self) -> System.Drawing.Point: ...
    def get_DeviceDpi(self) -> int: ...
    def get_DialogResult(self) -> System.Windows.Forms.DialogResult: ...
    def get_DisplayRectangle(self) -> System.Drawing.Rectangle: ...
    def get_Disposing(self) -> bool: ...
    def get_Dock(self) -> System.Windows.Forms.DockStyle: ...
    def get_DockPadding(self) -> Any: ...
    def get_DoubleBuffered(self) -> bool: ...
    def get_Enabled(self) -> bool: ...
    def get_Events(self) -> System.ComponentModel.EventHandlerList: ...
    def get_Focused(self) -> bool: ...
    def get_Font(self) -> System.Drawing.Font: ...
    def get_FontHeight(self) -> int: ...
    def get_ForeColor(self) -> System.Drawing.Color: ...
    def get_FormBorderStyle(self) -> System.Windows.Forms.FormBorderStyle: ...
    def get_HScroll(self) -> bool: ...
    def get_Handle(self) -> Any: ...
    def get_HasChildren(self) -> bool: ...
    def get_Height(self) -> int: ...
    def get_HelpButton(self) -> bool: ...
    def get_HorizontalScroll(self) -> System.Windows.Forms.HScrollProperties: ...
    def get_Icon(self) -> System.Drawing.Icon: ...
    def get_ImeMode(self) -> System.Windows.Forms.ImeMode: ...
    def get_ImeModeBase(self) -> System.Windows.Forms.ImeMode: ...
    def get_InvokeRequired(self) -> bool: ...
    def get_IsAccessible(self) -> bool: ...
    def get_IsDisposed(self) -> bool: ...
    def get_IsHandleCreated(self) -> bool: ...
    def get_IsMdiChild(self) -> bool: ...
    def get_IsMdiContainer(self) -> bool: ...
    def get_IsMirrored(self) -> bool: ...
    def get_IsRestrictedWindow(self) -> bool: ...
    def get_KeyPreview(self) -> bool: ...
    def get_LayoutEngine(self) -> System.Windows.Forms.Layout.LayoutEngine: ...
    def get_Left(self) -> int: ...
    def get_Location(self) -> System.Drawing.Point: ...
    def get_MainMenuStrip(self) -> System.Windows.Forms.MenuStrip: ...
    def get_Margin(self) -> System.Windows.Forms.Padding: ...
    def get_MaximizeBox(self) -> bool: ...
    def get_MaximizedBounds(self) -> System.Drawing.Rectangle: ...
    def get_MaximumSize(self) -> System.Drawing.Size: ...
    def get_MdiChildren(self) -> List[System.Windows.Forms.Form]: ...
    def get_MdiParent(self) -> System.Windows.Forms.Form: ...
    def get_Menu(self) -> System.Windows.Forms.MainMenu: ...
    def get_MergedMenu(self) -> System.Windows.Forms.MainMenu: ...
    def get_MinimizeBox(self) -> bool: ...
    def get_MinimumSize(self) -> System.Drawing.Size: ...
    def get_Modal(self) -> bool: ...
    def get_ModifierKeys(self) -> System.Windows.Forms.Keys: ...
    def get_MouseButtons(self) -> System.Windows.Forms.MouseButtons: ...
    def get_MousePosition(self) -> System.Drawing.Point: ...
    def get_Name(self) -> str: ...
    def get_Opacity(self) -> float: ...
    def get_OwnedForms(self) -> List[System.Windows.Forms.Form]: ...
    def get_Owner(self) -> System.Windows.Forms.Form: ...
    def get_Padding(self) -> System.Windows.Forms.Padding: ...
    def get_Parent(self) -> System.Windows.Forms.Control: ...
    def get_ParentForm(self) -> System.Windows.Forms.Form: ...
    def get_PreferredSize(self) -> System.Drawing.Size: ...
    def get_ProductName(self) -> str: ...
    def get_ProductVersion(self) -> str: ...
    def get_PropagatingImeMode(self) -> System.Windows.Forms.ImeMode: ...
    def get_RecreatingHandle(self) -> bool: ...
    def get_Region(self) -> System.Drawing.Region: ...
    def get_RenderRightToLeft(self) -> bool: ...
    def get_ResizeRedraw(self) -> bool: ...
    def get_RestoreBounds(self) -> System.Drawing.Rectangle: ...
    def get_Right(self) -> int: ...
    def get_RightToLeft(self) -> System.Windows.Forms.RightToLeft: ...
    def get_RightToLeftLayout(self) -> bool: ...
    def get_ScaleChildren(self) -> bool: ...
    def get_ShowFocusCues(self) -> bool: ...
    def get_ShowIcon(self) -> bool: ...
    def get_ShowInTaskbar(self) -> bool: ...
    def get_ShowKeyboardCues(self) -> bool: ...
    def get_ShowWithoutActivation(self) -> bool: ...
    def get_Site(self) -> System.ComponentModel.ISite: ...
    def get_Size(self) -> System.Drawing.Size: ...
    def get_SizeGripStyle(self) -> System.Windows.Forms.SizeGripStyle: ...
    def get_StartPosition(self) -> System.Windows.Forms.FormStartPosition: ...
    def get_TabIndex(self) -> int: ...
    def get_TabStop(self) -> bool: ...
    def get_Tag(self) -> object: ...
    def get_Text(self) -> str: ...
    def get_Top(self) -> int: ...
    def get_TopLevel(self) -> bool: ...
    def get_TopLevelControl(self) -> System.Windows.Forms.Control: ...
    def get_TopMost(self) -> bool: ...
    def get_TransparencyKey(self) -> System.Drawing.Color: ...
    def get_UseWaitCursor(self) -> bool: ...
    def get_VScroll(self) -> bool: ...
    def get_VerticalScroll(self) -> System.Windows.Forms.VScrollProperties: ...
    def get_Visible(self) -> bool: ...
    def get_Width(self) -> int: ...
    def get_WindowState(self) -> System.Windows.Forms.FormWindowState: ...
    def get_WindowTarget(self) -> System.Windows.Forms.IWindowTarget: ...
    def remove_Activated(self, _: Any) -> None: ...
    def remove_AutoSizeChanged(self, _: Any) -> None: ...
    def remove_AutoValidateChanged(self, _: Any) -> None: ...
    def remove_BackColorChanged(self, _: Any) -> None: ...
    def remove_BackgroundImageChanged(self, _: Any) -> None: ...
    def remove_BackgroundImageLayoutChanged(self, _: Any) -> None: ...
    def remove_BindingContextChanged(self, _: Any) -> None: ...
    def remove_CausesValidationChanged(self, _: Any) -> None: ...
    def remove_ChangeUICues(self, _: System.Windows.Forms.UICuesEventHandler) -> None: ...
    def remove_Click(self, _: Any) -> None: ...
    def remove_ClientSizeChanged(self, _: Any) -> None: ...
    def remove_Closed(self, _: Any) -> None: ...
    def remove_Closing(self, _: System.ComponentModel.CancelEventHandler) -> None: ...
    def remove_ContextMenuChanged(self, _: Any) -> None: ...
    def remove_ContextMenuStripChanged(self, _: Any) -> None: ...
    def remove_ControlAdded(self, _: System.Windows.Forms.ControlEventHandler) -> None: ...

    def remove_ControlRemoved(
            self,
            _: System.Windows.Forms.ControlEventHandler,
            ) -> None: ...

    def remove_CursorChanged(self, _: Any) -> None: ...
    def remove_Deactivate(self, _: Any) -> None: ...
    def remove_Disposed(self, _: Any) -> None: ...
    def remove_DockChanged(self, _: Any) -> None: ...
    def remove_DoubleClick(self, _: Any) -> None: ...
    def remove_DpiChanged(self, _: System.Windows.Forms.DpiChangedEventHandler) -> None: ...
    def remove_DpiChangedAfterParent(self, _: Any) -> None: ...
    def remove_DpiChangedBeforeParent(self, _: Any) -> None: ...
    def remove_DragDrop(self, _: System.Windows.Forms.DragEventHandler) -> None: ...
    def remove_DragEnter(self, _: System.Windows.Forms.DragEventHandler) -> None: ...
    def remove_DragLeave(self, _: Any) -> None: ...
    def remove_DragOver(self, _: System.Windows.Forms.DragEventHandler) -> None: ...
    def remove_EnabledChanged(self, _: Any) -> None: ...
    def remove_Enter(self, _: Any) -> None: ...
    def remove_FontChanged(self, _: Any) -> None: ...
    def remove_ForeColorChanged(self, _: Any) -> None: ...
    def remove_FormClosed(self, _: System.Windows.Forms.FormClosedEventHandler) -> None: ...

    def remove_FormClosing(
            self,
            _: System.Windows.Forms.FormClosingEventHandler,
            ) -> None: ...

    def remove_GiveFeedback(
            self,
            _: System.Windows.Forms.GiveFeedbackEventHandler,
            ) -> None: ...

    def remove_GotFocus(self, _: Any) -> None: ...
    def remove_HandleCreated(self, _: Any) -> None: ...
    def remove_HandleDestroyed(self, _: Any) -> None: ...

    def remove_HelpButtonClicked(
            self,
            _: System.ComponentModel.CancelEventHandler,
            ) -> None: ...

    def remove_HelpRequested(self, _: System.Windows.Forms.HelpEventHandler) -> None: ...
    def remove_ImeModeChanged(self, _: Any) -> None: ...

    def remove_InputLanguageChanged(
            self,
            _: System.Windows.Forms.InputLanguageChangedEventHandler,
            ) -> None: ...

    def remove_InputLanguageChanging(
            self,
            _: System.Windows.Forms.InputLanguageChangingEventHandler,
            ) -> None: ...

    def remove_Invalidated(
            self,
            _: System.Windows.Forms.InvalidateEventHandler,
            ) -> None: ...

    def remove_KeyDown(self, _: System.Windows.Forms.KeyEventHandler) -> None: ...
    def remove_KeyPress(self, _: System.Windows.Forms.KeyPressEventHandler) -> None: ...
    def remove_KeyUp(self, _: System.Windows.Forms.KeyEventHandler) -> None: ...
    def remove_Layout(self, _: System.Windows.Forms.LayoutEventHandler) -> None: ...
    def remove_Leave(self, _: Any) -> None: ...
    def remove_Load(self, _: Any) -> None: ...
    def remove_LocationChanged(self, _: Any) -> None: ...
    def remove_LostFocus(self, _: Any) -> None: ...
    def remove_MarginChanged(self, _: Any) -> None: ...
    def remove_MaximizedBoundsChanged(self, _: Any) -> None: ...
    def remove_MaximumSizeChanged(self, _: Any) -> None: ...
    def remove_MdiChildActivate(self, _: Any) -> None: ...
    def remove_MenuComplete(self, _: Any) -> None: ...
    def remove_MenuStart(self, _: Any) -> None: ...
    def remove_MinimumSizeChanged(self, _: Any) -> None: ...
    def remove_MouseCaptureChanged(self, _: Any) -> None: ...
    def remove_MouseClick(self, _: System.Windows.Forms.MouseEventHandler) -> None: ...

    def remove_MouseDoubleClick(
            self,
            _: System.Windows.Forms.MouseEventHandler,
            ) -> None: ...

    def remove_MouseDown(self, _: System.Windows.Forms.MouseEventHandler) -> None: ...
    def remove_MouseEnter(self, _: Any) -> None: ...
    def remove_MouseHover(self, _: Any) -> None: ...
    def remove_MouseLeave(self, _: Any) -> None: ...
    def remove_MouseMove(self, _: System.Windows.Forms.MouseEventHandler) -> None: ...
    def remove_MouseUp(self, _: System.Windows.Forms.MouseEventHandler) -> None: ...
    def remove_MouseWheel(self, _: System.Windows.Forms.MouseEventHandler) -> None: ...
    def remove_Move(self, _: Any) -> None: ...
    def remove_PaddingChanged(self, _: Any) -> None: ...
    def remove_Paint(self, _: System.Windows.Forms.PaintEventHandler) -> None: ...
    def remove_ParentChanged(self, _: Any) -> None: ...

    def remove_PreviewKeyDown(
            self,
            _: System.Windows.Forms.PreviewKeyDownEventHandler,
            ) -> None: ...

    def remove_QueryAccessibilityHelp(
            self,
            _: System.Windows.Forms.QueryAccessibilityHelpEventHandler,
            ) -> None: ...

    def remove_QueryContinueDrag(
            self,
            _: System.Windows.Forms.QueryContinueDragEventHandler,
            ) -> None: ...

    def remove_RegionChanged(self, _: Any) -> None: ...
    def remove_Resize(self, _: Any) -> None: ...
    def remove_ResizeBegin(self, _: Any) -> None: ...
    def remove_ResizeEnd(self, _: Any) -> None: ...
    def remove_RightToLeftChanged(self, _: Any) -> None: ...
    def remove_RightToLeftLayoutChanged(self, _: Any) -> None: ...
    def remove_Scroll(self, _: System.Windows.Forms.ScrollEventHandler) -> None: ...
    def remove_Shown(self, _: Any) -> None: ...
    def remove_SizeChanged(self, _: Any) -> None: ...
    def remove_StyleChanged(self, _: Any) -> None: ...
    def remove_SystemColorsChanged(self, _: Any) -> None: ...
    def remove_TabIndexChanged(self, _: Any) -> None: ...
    def remove_TabStopChanged(self, _: Any) -> None: ...
    def remove_TextChanged(self, _: Any) -> None: ...
    def remove_Validated(self, _: Any) -> None: ...
    def remove_Validating(self, _: System.ComponentModel.CancelEventHandler) -> None: ...
    def remove_VisibleChanged(self, _: Any) -> None: ...
    def set_AcceptButton(self, _: System.Windows.Forms.IButtonControl) -> None: ...
    def set_AccessibleDefaultActionDescription(self, _: str) -> None: ...
    def set_AccessibleDescription(self, _: str) -> None: ...
    def set_AccessibleName(self, _: str) -> None: ...
    def set_AccessibleRole(self, _: System.Windows.Forms.AccessibleRole) -> None: ...
    def set_ActiveControl(self, _: System.Windows.Forms.Control) -> None: ...
    def set_AllowDrop(self, _: bool) -> None: ...
    def set_AllowTransparency(self, _: bool) -> None: ...
    def set_Anchor(self, _: System.Windows.Forms.AnchorStyles) -> None: ...
    def set_AutoScale(self, _: bool) -> None: ...
    def set_AutoScaleBaseSize(self, _: System.Drawing.Size) -> None: ...
    def set_AutoScaleDimensions(self, _: System.Drawing.SizeF) -> None: ...
    def set_AutoScaleMode(self, _: System.Windows.Forms.AutoScaleMode) -> None: ...
    def set_AutoScroll(self, _: bool) -> None: ...
    def set_AutoScrollMargin(self, _: System.Drawing.Size) -> None: ...
    def set_AutoScrollMinSize(self, _: System.Drawing.Size) -> None: ...
    def set_AutoScrollOffset(self, _: System.Drawing.Point) -> None: ...
    def set_AutoScrollPosition(self, _: System.Drawing.Point) -> None: ...
    def set_AutoSize(self, _: bool) -> None: ...
    def set_AutoSizeMode(self, _: System.Windows.Forms.AutoSizeMode) -> None: ...
    def set_AutoValidate(self, _: System.Windows.Forms.AutoValidate) -> None: ...
    def set_BackColor(self, _: System.Drawing.Color) -> None: ...
    def set_BackgroundImage(self, _: System.Drawing.Image) -> None: ...
    def set_BackgroundImageLayout(self, _: System.Windows.Forms.ImageLayout) -> None: ...
    def set_BindingContext(self, _: System.Windows.Forms.BindingContext) -> None: ...
    def set_Bounds(self, _: System.Drawing.Rectangle) -> None: ...
    def set_CancelButton(self, _: System.Windows.Forms.IButtonControl) -> None: ...
    def set_Capture(self, _: bool) -> None: ...
    def set_CausesValidation(self, _: bool) -> None: ...
    def set_CheckForIllegalCrossThreadCalls(self, _: bool) -> None: ...
    def set_ClientSize(self, _: System.Drawing.Size) -> None: ...
    def set_ContextMenu(self, _: System.Windows.Forms.ContextMenu) -> None: ...
    def set_ContextMenuStrip(self, _: System.Windows.Forms.ContextMenuStrip) -> None: ...
    def set_ControlBox(self, _: bool) -> None: ...
    def set_Cursor(self, _: System.Windows.Forms.Cursor) -> None: ...
    def set_DesktopBounds(self, _: System.Drawing.Rectangle) -> None: ...
    def set_DesktopLocation(self, _: System.Drawing.Point) -> None: ...
    def set_DialogResult(self, _: System.Windows.Forms.DialogResult) -> None: ...
    def set_Dock(self, _: System.Windows.Forms.DockStyle) -> None: ...
    def set_DoubleBuffered(self, _: bool) -> None: ...
    def set_Enabled(self, _: bool) -> None: ...
    def set_Font(self, _: System.Drawing.Font) -> None: ...
    def set_FontHeight(self, _: int) -> None: ...
    def set_ForeColor(self, _: System.Drawing.Color) -> None: ...
    def set_FormBorderStyle(self, _: System.Windows.Forms.FormBorderStyle) -> None: ...
    def set_HScroll(self, _: bool) -> None: ...
    def set_Height(self, _: int) -> None: ...
    def set_HelpButton(self, _: bool) -> None: ...
    def set_Icon(self, _: System.Drawing.Icon) -> None: ...
    def set_ImeMode(self, _: System.Windows.Forms.ImeMode) -> None: ...
    def set_ImeModeBase(self, _: System.Windows.Forms.ImeMode) -> None: ...
    def set_IsAccessible(self, _: bool) -> None: ...
    def set_IsMdiContainer(self, _: bool) -> None: ...
    def set_KeyPreview(self, _: bool) -> None: ...
    def set_Left(self, _: int) -> None: ...
    def set_Location(self, _: System.Drawing.Point) -> None: ...
    def set_MainMenuStrip(self, _: System.Windows.Forms.MenuStrip) -> None: ...
    def set_Margin(self, _: System.Windows.Forms.Padding) -> None: ...
    def set_MaximizeBox(self, _: bool) -> None: ...
    def set_MaximizedBounds(self, _: System.Drawing.Rectangle) -> None: ...
    def set_MaximumSize(self, _: System.Drawing.Size) -> None: ...
    def set_MdiParent(self, _: System.Windows.Forms.Form) -> None: ...
    def set_Menu(self, _: System.Windows.Forms.MainMenu) -> None: ...
    def set_MinimizeBox(self, _: bool) -> None: ...
    def set_MinimumSize(self, _: System.Drawing.Size) -> None: ...
    def set_Name(self, _: str) -> None: ...
    def set_Opacity(self, _: float) -> None: ...
    def set_Owner(self, _: System.Windows.Forms.Form) -> None: ...
    def set_Padding(self, _: System.Windows.Forms.Padding) -> None: ...
    def set_Parent(self, _: System.Windows.Forms.Control) -> None: ...
    def set_Region(self, _: System.Drawing.Region) -> None: ...
    def set_ResizeRedraw(self, _: bool) -> None: ...
    def set_RightToLeft(self, _: System.Windows.Forms.RightToLeft) -> None: ...
    def set_RightToLeftLayout(self, _: bool) -> None: ...
    def set_ShowIcon(self, _: bool) -> None: ...
    def set_ShowInTaskbar(self, _: bool) -> None: ...
    def set_Site(self, _: System.ComponentModel.ISite) -> None: ...
    def set_Size(self, _: System.Drawing.Size) -> None: ...
    def set_SizeGripStyle(self, _: System.Windows.Forms.SizeGripStyle) -> None: ...
    def set_StartPosition(self, _: System.Windows.Forms.FormStartPosition) -> None: ...
    def set_TabIndex(self, _: int) -> None: ...
    def set_TabStop(self, _: bool) -> None: ...
    def set_Tag(self, _: object) -> None: ...
    def set_Text(self, _: str) -> None: ...
    def set_Top(self, _: int) -> None: ...
    def set_TopLevel(self, _: bool) -> None: ...
    def set_TopMost(self, _: bool) -> None: ...
    def set_TransparencyKey(self, _: System.Drawing.Color) -> None: ...
    def set_UseWaitCursor(self, _: bool) -> None: ...
    def set_VScroll(self, _: bool) -> None: ...
    def set_Visible(self, _: bool) -> None: ...
    def set_Width(self, _: int) -> None: ...
    def set_WindowState(self, _: System.Windows.Forms.FormWindowState) -> None: ...
    def set_WindowTarget(self, _: System.Windows.Forms.IWindowTarget) -> None: ...


class WinFormsOverlayManager:

    def __init__(self, *args, **kwargs) -> Any: ...
    def Dispose(self) -> None: ...
    def Equals(self, _: object, __: object) -> bool: ...
    def Finalize(self) -> None: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...

    @property
    def Margin(self): ...

    @Margin.setter
    def Margin(self, value): ...

    def MemberwiseClone(self) -> object: ...
    def Overloads(self, *args, **kwargs) -> Any: ...
    def ReferenceEquals(self, _: object, __: object) -> bool: ...

    def Show(
            self,
            _: System.Drawing.Rectangle,
            __: System.Drawing.Color,
            ___: int,
            ) -> None: ...

    def ShowBlocking(
            self,
            _: System.Drawing.Rectangle,
            __: System.Drawing.Color,
            ___: int,
            ) -> None: ...

    @property
    def Size(self): ...

    @Size.setter
    def Size(self, value): ...

    def ToString(self) -> str: ...
    def get_Margin(self) -> int: ...
    def get_Size(self) -> int: ...
    def set_Margin(self, _: int) -> None: ...
    def set_Size(self, _: int) -> None: ...
