from __future__ import annotations

from typing import Any
from typing import List
from typing import Type

import System
import System.Collections
import System.ComponentModel
import System.Configuration
import System.Configuration.Assemblies
import System.Data
import System.Globalization
import System.IO
import System.Reflection
import System.Runtime
import System.Runtime.CompilerServices
import System.Runtime.InteropServices
import System.Runtime.Remoting
import System.Runtime.Serialization
import System.Security
import System.Security.AccessControl
import System.Security.Cryptography
import System.Security.Cryptography.X509Certificates
import System.Security.Policy
import System.Security.Principal
import System.Threading
import System.Threading.Tasks
import System.Xml
import System.Xml.Schema
import System.Xml.Serialization
from System.ComponentModel import MarshalByValueComponent


class ActiveTextPositionChangedEventHandlerBase:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Automation(self): ...

    @Automation.setter
    def Automation(self, value): ...

    def Dispose(self) -> None: ...
    def Equals(self, _: object, __: object) -> bool: ...
    def Finalize(self) -> None: ...

    @property
    def FrameworkElement(self): ...

    @FrameworkElement.setter
    def FrameworkElement(self, value): ...

    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...

    def HandleActiveTextPositionChangedEvent(
            self,
            _: AutomationElement,
            __: ITextRange,
            ) -> None: ...

    def MemberwiseClone(self) -> object: ...
    def Overloads(self, *args, **kwargs) -> Any: ...
    def ReferenceEquals(self, _: object, __: object) -> bool: ...
    def ToString(self) -> str: ...
    def UnregisterEventHandler(self) -> None: ...
    def get_Automation(self) -> AutomationBase: ...
    def get_FrameworkElement(self) -> FrameworkAutomationElementBase: ...


class AutomationEventHandlerBase:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Automation(self): ...

    @Automation.setter
    def Automation(self, value): ...

    def Dispose(self) -> None: ...
    def Equals(self, _: object, __: object) -> bool: ...

    @property
    def Event(self): ...

    @Event.setter
    def Event(self, value): ...

    def Finalize(self) -> None: ...

    @property
    def FrameworkElement(self): ...

    @FrameworkElement.setter
    def FrameworkElement(self, value): ...

    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    def HandleAutomationEvent(self, _: AutomationElement, __: EventId) -> None: ...
    def MemberwiseClone(self) -> object: ...
    def Overloads(self, *args, **kwargs) -> Any: ...
    def ReferenceEquals(self, _: object, __: object) -> bool: ...
    def ToString(self) -> str: ...
    def UnregisterEventHandler(self) -> None: ...
    def get_Automation(self) -> AutomationBase: ...
    def get_Event(self) -> EventId: ...
    def get_FrameworkElement(self) -> FrameworkAutomationElementBase: ...


class ElementEventHandlerBase:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Automation(self): ...

    @Automation.setter
    def Automation(self, value): ...

    def Dispose(self) -> None: ...
    def Equals(self, _: object, __: object) -> bool: ...
    def Finalize(self) -> None: ...

    @property
    def FrameworkElement(self): ...

    @FrameworkElement.setter
    def FrameworkElement(self, value): ...

    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    def MemberwiseClone(self) -> object: ...
    def Overloads(self, *args, **kwargs) -> Any: ...
    def ReferenceEquals(self, _: object, __: object) -> bool: ...
    def ToString(self) -> str: ...
    def UnregisterEventHandler(self) -> None: ...
    def get_Automation(self) -> AutomationBase: ...
    def get_FrameworkElement(self) -> FrameworkAutomationElementBase: ...


class EventHandlerBase:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Automation(self): ...

    @Automation.setter
    def Automation(self, value): ...

    def Dispose(self) -> None: ...
    def Equals(self, _: object, __: object) -> bool: ...
    def Finalize(self) -> None: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    def MemberwiseClone(self) -> object: ...
    def Overloads(self, *args, **kwargs) -> Any: ...
    def ReferenceEquals(self, _: object, __: object) -> bool: ...
    def ToString(self) -> str: ...
    def UnregisterEventHandler(self) -> None: ...
    def get_Automation(self) -> AutomationBase: ...


class FocusChangedEventHandlerBase:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Automation(self): ...

    @Automation.setter
    def Automation(self, value): ...

    def Dispose(self) -> None: ...
    def Equals(self, _: object, __: object) -> bool: ...
    def Finalize(self) -> None: ...
    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...
    def HandleFocusChangedEvent(self, _: AutomationElement) -> None: ...
    def MemberwiseClone(self) -> object: ...
    def Overloads(self, *args, **kwargs) -> Any: ...
    def ReferenceEquals(self, _: object, __: object) -> bool: ...
    def ToString(self) -> str: ...
    def UnregisterEventHandler(self) -> None: ...
    def get_Automation(self) -> AutomationBase: ...


class NotificationEventHandlerBase:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Automation(self): ...

    @Automation.setter
    def Automation(self, value): ...

    def Dispose(self) -> None: ...
    def Equals(self, _: object, __: object) -> bool: ...
    def Finalize(self) -> None: ...

    @property
    def FrameworkElement(self): ...

    @FrameworkElement.setter
    def FrameworkElement(self, value): ...

    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...

    def HandleNotificationEvent(
            self,
            _: AutomationElement,
            __: NotificationKind,
            ___: NotificationProcessing,
            ____: str,
            _____: str,
            ) -> None: ...

    def MemberwiseClone(self) -> object: ...
    def Overloads(self, *args, **kwargs) -> Any: ...
    def ReferenceEquals(self, _: object, __: object) -> bool: ...
    def ToString(self) -> str: ...
    def UnregisterEventHandler(self) -> None: ...
    def get_Automation(self) -> AutomationBase: ...
    def get_FrameworkElement(self) -> FrameworkAutomationElementBase: ...


class PropertyChangedEventHandlerBase:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Automation(self): ...

    @Automation.setter
    def Automation(self, value): ...

    def Dispose(self) -> None: ...
    def Equals(self, _: object, __: object) -> bool: ...
    def Finalize(self) -> None: ...

    @property
    def FrameworkElement(self): ...

    @FrameworkElement.setter
    def FrameworkElement(self, value): ...

    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...

    def HandlePropertyChangedEvent(
            self,
            _: AutomationElement,
            __: PropertyId,
            ___: object,
            ) -> None: ...

    def MemberwiseClone(self) -> object: ...
    def Overloads(self, *args, **kwargs) -> Any: ...
    def ReferenceEquals(self, _: object, __: object) -> bool: ...
    def ToString(self) -> str: ...
    def UnregisterEventHandler(self) -> None: ...
    def get_Automation(self) -> AutomationBase: ...
    def get_FrameworkElement(self) -> FrameworkAutomationElementBase: ...


class StructureChangedEventHandlerBase:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Automation(self): ...

    @Automation.setter
    def Automation(self, value): ...

    def Dispose(self) -> None: ...
    def Equals(self, _: object, __: object) -> bool: ...
    def Finalize(self) -> None: ...

    @property
    def FrameworkElement(self): ...

    @FrameworkElement.setter
    def FrameworkElement(self, value): ...

    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...

    def HandleStructureChangedEvent(
            self,
            _: AutomationElement,
            __: StructureChangeType,
            ___: List[int],
            ) -> None: ...

    def MemberwiseClone(self) -> object: ...
    def Overloads(self, *args, **kwargs) -> Any: ...
    def ReferenceEquals(self, _: object, __: object) -> bool: ...
    def ToString(self) -> str: ...
    def UnregisterEventHandler(self) -> None: ...
    def get_Automation(self) -> AutomationBase: ...
    def get_FrameworkElement(self) -> FrameworkAutomationElementBase: ...


class TextEditTextChangedEventHandlerBase:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Automation(self): ...

    @Automation.setter
    def Automation(self, value): ...

    def Dispose(self) -> None: ...
    def Equals(self, _: object, __: object) -> bool: ...
    def Finalize(self) -> None: ...

    @property
    def FrameworkElement(self): ...

    @FrameworkElement.setter
    def FrameworkElement(self, value): ...

    def GetHashCode(self) -> int: ...
    def GetType(self) -> Type: ...

    def HandleTextEditTextChangedEvent(
            self,
            _: AutomationElement,
            __: TextEditChangeType,
            ___: List[str],
            ) -> None: ...

    def MemberwiseClone(self) -> object: ...
    def Overloads(self, *args, **kwargs) -> Any: ...
    def ReferenceEquals(self, _: object, __: object) -> bool: ...
    def ToString(self) -> str: ...
    def UnregisterEventHandler(self) -> None: ...
    def get_Automation(self) -> AutomationBase: ...
    def get_FrameworkElement(self) -> FrameworkAutomationElementBase: ...
