"""Generate docs/changelog.md from the project's GitHub Releases.

Fetches published releases from the GitHub REST API and renders their Markdown
notes into a single docs page. Run as a pre-build step alongside
``extract_versions.py`` so the docs site always carries the latest release notes.

The script is **build-safe**: any network/API failure (offline local builds,
rate limits) is swallowed and a small fallback page is written instead, so a
strict ``zensical build`` never fails just because releases could not be fetched.

Authentication is optional but recommended in CI: set ``GITHUB_TOKEN`` to raise
the unauthenticated rate limit. The repository is taken from
``GITHUB_REPOSITORY`` (set automatically in GitHub Actions) and falls back to the
canonical slug below.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import sys
from typing import Any, Dict, List
import urllib.error
import urllib.request

ROOT = Path(__file__).resolve().parent.parent
OUTPUT_MD = ROOT / "docs" / "changelog.md"
DEFAULT_REPO = "amruthvvkp/flaui-uiautomation-wrapper"

HEADER = (
    "<!-- Auto-generated by scripts/build_changelog.py from GitHub Releases. "
    "Do not edit manually. -->"
)


def _repo() -> str:
    """Return the ``owner/name`` slug for the GitHub repository."""
    return os.environ.get("GITHUB_REPOSITORY") or DEFAULT_REPO


def fetch_releases(repo: str) -> List[Dict[str, Any]]:
    """Fetch published releases for ``repo`` from the GitHub REST API.

    :param repo: Repository slug in ``owner/name`` form.
    :return: List of release objects (newest first), excluding drafts.
    :raises urllib.error.URLError: If the API cannot be reached.
    """
    url = f"https://api.github.com/repos/{repo}/releases?per_page=100"
    request = urllib.request.Request(url)
    request.add_header("Accept", "application/vnd.github+json")
    request.add_header("X-GitHub-Api-Version", "2022-11-28")
    request.add_header("User-Agent", "flaui-uiautomation-wrapper-docs")
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        request.add_header("Authorization", f"Bearer {token}")

    with urllib.request.urlopen(request, timeout=30) as resp:
        data = json.load(resp)
    # Drop drafts; keep pre-releases (betas) and stable releases.
    return [rel for rel in data if not rel.get("draft", False)]


def _demote_headings(body: str) -> str:
    """Demote Markdown headings by one level so they nest under the release H2.

    Release notes commonly start their own ``# Changelog`` H1; shifting every
    heading down one level (capped at H6) keeps the page's heading hierarchy and
    table of contents coherent.

    :param body: Raw release body Markdown.
    :return: Body with ATX headings demoted one level.
    """
    out: List[str] = []
    in_fence = False
    for line in body.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            in_fence = not in_fence
            out.append(line)
            continue
        if not in_fence and stripped.startswith("#"):
            hashes = len(stripped) - len(stripped.lstrip("#"))
            if 1 <= hashes <= 5 and stripped[hashes : hashes + 1] in ("", " "):
                line = "#" + line
        out.append(line)
    return "\n".join(out)


def build_markdown(releases: List[Dict[str, Any]], repo: str) -> str:
    """Render fetched releases into the changelog page Markdown.

    :param releases: Release objects as returned by :func:`fetch_releases`.
    :param repo: Repository slug, used for the "view on GitHub" link.
    :return: Complete Markdown document.
    """
    releases_url = f"https://github.com/{repo}/releases"
    lines = [
        HEADER,
        "# Changelog",
        "",
        f"Release notes are sourced live from [GitHub Releases]({releases_url}) "
        "at documentation build time.",
        "",
    ]

    if not releases:
        lines += [
            "_No releases have been published yet._ "
            f"Watch [GitHub Releases]({releases_url}) for the first one.",
            "",
        ]
        return "\n".join(lines)

    for rel in releases:
        title = rel.get("name") or rel.get("tag_name") or "Untitled release"
        html_url = rel.get("html_url") or releases_url
        published = (rel.get("published_at") or rel.get("created_at") or "")[:10]
        badges = []
        if published:
            badges.append(published)
        if rel.get("prerelease"):
            badges.append("pre-release")
        suffix = f" — {' · '.join(badges)}" if badges else ""

        lines.append(f"## [{title}]({html_url}){suffix}")
        lines.append("")
        body = (rel.get("body") or "").strip()
        if body:
            lines.append(_demote_headings(body))
        else:
            lines.append("_No release notes provided._")
        lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _fallback_markdown(repo: str, reason: str) -> str:
    """Build a minimal page used when releases cannot be fetched.

    :param repo: Repository slug for the GitHub link.
    :param reason: Short human-readable explanation (logged, not rendered).
    :return: Fallback Markdown document.
    """
    releases_url = f"https://github.com/{repo}/releases"
    return "\n".join(
        [
            HEADER,
            "# Changelog",
            "",
            f"Release notes could not be fetched at build time ({reason}).",
            "",
            f"See the full list on [GitHub Releases]({releases_url}).",
            "",
        ]
    )


def main() -> int:
    repo = _repo()
    OUTPUT_MD.parent.mkdir(parents=True, exist_ok=True)

    try:
        releases = fetch_releases(repo)
    except (urllib.error.URLError, TimeoutError, OSError, ValueError) as exc:
        # Build-safe: never fail the docs build because releases are unreachable.
        reason = type(exc).__name__
        print(f"WARNING: could not fetch releases for {repo}: {exc}", file=sys.stderr)
        OUTPUT_MD.write_text(_fallback_markdown(repo, reason), encoding="utf-8")
        print(f"Written fallback changelog: {OUTPUT_MD.relative_to(ROOT)}")
        return 0

    OUTPUT_MD.write_text(build_markdown(releases, repo), encoding="utf-8")
    print(f"Fetched {len(releases)} release(s) from {repo}")
    print(f"Written: {OUTPUT_MD.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
