"""Generate a reusable Markdown snippet with FlaUI binary versions.

Parses flaui/bin/Version.md and writes docs/includes/flaui_versions.md.
This keeps docs in sync whenever the packaged FlaUI DLLs are updated.
"""

from __future__ import annotations

from pathlib import Path
import sys
from typing import Dict, List

ROOT = Path(__file__).resolve().parent.parent
VERSION_MD = ROOT / "flaui" / "bin" / "Version.md"
OUTPUT_MD = ROOT / "docs" / "_includes" / "flaui_versions.md"


def parse_version_table(lines: List[str]) -> List[Dict[str, str]]:
    rows: List[Dict[str, str]] = []
    for line in lines:
        stripped = line.strip()
        if not stripped or not stripped.startswith("|"):
            # Stop when we leave the table
            if rows:
                break
            continue
        # Skip separator and header lines
        if set(stripped.replace("|", "").strip()) in ({"-"}, {"-", " "}):
            continue
        cells = [cell.strip() for cell in stripped.strip("|").split("|")]
        if cells and cells[0].lower() == "library":
            continue
        if len(cells) < 5:
            continue
        rows.append(
            {
                "library": cells[0],
                "version": cells[1],
                "framework": cells[2],
                "dependency": cells[3],
                "license": cells[4],
            }
        )
    return rows


def build_markdown(rows: List[Dict[str, str]]) -> str:
    lines = [
        "<!-- Auto-generated by scripts/extract_versions.py. Do not edit manually. -->",
        "# FlaUI Binary Versions",
        "",
        "| Library | Version | Framework | Dependency | License |",
        "| --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            f"| {row['library']} | {row['version']} | {row['framework']} | {row['dependency']} | {row['license']} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not VERSION_MD.exists():
        print(f"Version file not found: {VERSION_MD}", file=sys.stderr)
        return 1

    lines = VERSION_MD.read_text(encoding="utf-8").splitlines()
    rows = parse_version_table(lines)
    if not rows:
        print("No version rows parsed from Version.md", file=sys.stderr)
        return 1

    OUTPUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_MD.write_text(build_markdown(rows), encoding="utf-8")

    print("FlaUI versions:")
    for row in rows:
        print(f"  {row['library']}: {row['version']} ({row['framework']})")

    print(f"Written: {OUTPUT_MD.relative_to(ROOT)}")
    return 0


def on_startup(command, dirty):
    """MkDocs hook: Run extraction before build."""
    print("Hook: Extracting FlaUI versions...")
    main()


if __name__ == "__main__":
    raise SystemExit(main())
