from __future__ import annotations

from typing import Any
from typing import Type

import System
import System.Collections
import System.ComponentModel
import System.Configuration
import System.Configuration.Assemblies
import System.Data
import System.Globalization
import System.IO
import System.Reflection
import System.Runtime
import System.Runtime.CompilerServices
import System.Runtime.InteropServices
import System.Runtime.Remoting
import System.Runtime.Serialization
import System.Security
import System.Security.AccessControl
import System.Security.Cryptography
import System.Security.Cryptography.X509Certificates
import System.Security.Policy
import System.Security.Principal
import System.Threading
import System.Threading.Tasks
import System.Xml
import System.Xml.Schema
import System.Xml.Serialization
from System.ComponentModel import MarshalByValueComponent


class ElementNotAvailableException:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Data(self): ...

    @Data.setter
    def Data(self, value): ...

    def GetBaseException(self) -> Exception: ...

    def GetObjectData(
            self,
            _: System.Runtime.Serialization.SerializationInfo,
            __: System.Runtime.Serialization.StreamingContext,
            ) -> None: ...

    def GetType(self) -> Type: ...

    @property
    def HResult(self): ...

    @HResult.setter
    def HResult(self, value): ...

    @property
    def HelpLink(self): ...

    @HelpLink.setter
    def HelpLink(self, value): ...

    @property
    def InnerException(self): ...

    @InnerException.setter
    def InnerException(self, value): ...

    @property
    def Message(self): ...

    @Message.setter
    def Message(self, value): ...

    def Overloads(self, *args, **kwargs) -> Any: ...
    def SerializeObjectState(self, *args, **kwargs) -> Any: ...

    @property
    def Source(self): ...

    @Source.setter
    def Source(self, value): ...

    @property
    def StackTrace(self): ...

    @StackTrace.setter
    def StackTrace(self, value): ...

    @property
    def TargetSite(self): ...

    @TargetSite.setter
    def TargetSite(self, value): ...

    def ToString(self) -> str: ...
    def add_SerializeObjectState(self, _: Any) -> None: ...
    def args(self, *args, **kwargs) -> Any: ...
    def get_Data(self) -> System.Collections.IDictionary: ...
    def get_HResult(self) -> int: ...
    def get_HelpLink(self) -> str: ...
    def get_InnerException(self) -> Exception: ...
    def get_Message(self) -> str: ...
    def get_Source(self) -> str: ...
    def get_StackTrace(self) -> str: ...
    def get_TargetSite(self) -> System.Reflection.MethodBase: ...
    def remove_SerializeObjectState(self, _: Any) -> None: ...
    def set_HResult(self, _: int) -> None: ...
    def set_HelpLink(self, _: str) -> None: ...
    def set_Source(self, _: str) -> None: ...
    def with_traceback(self, *args, **kwargs) -> Any: ...


class ElementNotEnabledException:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Data(self): ...

    @Data.setter
    def Data(self, value): ...

    def GetBaseException(self) -> Exception: ...

    def GetObjectData(
            self,
            _: System.Runtime.Serialization.SerializationInfo,
            __: System.Runtime.Serialization.StreamingContext,
            ) -> None: ...

    def GetType(self) -> Type: ...

    @property
    def HResult(self): ...

    @HResult.setter
    def HResult(self, value): ...

    @property
    def HelpLink(self): ...

    @HelpLink.setter
    def HelpLink(self, value): ...

    @property
    def InnerException(self): ...

    @InnerException.setter
    def InnerException(self, value): ...

    @property
    def Message(self): ...

    @Message.setter
    def Message(self, value): ...

    def Overloads(self, *args, **kwargs) -> Any: ...
    def SerializeObjectState(self, *args, **kwargs) -> Any: ...

    @property
    def Source(self): ...

    @Source.setter
    def Source(self, value): ...

    @property
    def StackTrace(self): ...

    @StackTrace.setter
    def StackTrace(self, value): ...

    @property
    def TargetSite(self): ...

    @TargetSite.setter
    def TargetSite(self, value): ...

    def ToString(self) -> str: ...
    def add_SerializeObjectState(self, _: Any) -> None: ...
    def args(self, *args, **kwargs) -> Any: ...
    def get_Data(self) -> System.Collections.IDictionary: ...
    def get_HResult(self) -> int: ...
    def get_HelpLink(self) -> str: ...
    def get_InnerException(self) -> Exception: ...
    def get_Message(self) -> str: ...
    def get_Source(self) -> str: ...
    def get_StackTrace(self) -> str: ...
    def get_TargetSite(self) -> System.Reflection.MethodBase: ...
    def remove_SerializeObjectState(self, _: Any) -> None: ...
    def set_HResult(self, _: int) -> None: ...
    def set_HelpLink(self, _: str) -> None: ...
    def set_Source(self, _: str) -> None: ...
    def with_traceback(self, *args, **kwargs) -> Any: ...


class FlaUIException:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Data(self): ...

    @Data.setter
    def Data(self, value): ...

    def GetBaseException(self) -> Exception: ...

    def GetObjectData(
            self,
            _: System.Runtime.Serialization.SerializationInfo,
            __: System.Runtime.Serialization.StreamingContext,
            ) -> None: ...

    def GetType(self) -> Type: ...

    @property
    def HResult(self): ...

    @HResult.setter
    def HResult(self, value): ...

    @property
    def HelpLink(self): ...

    @HelpLink.setter
    def HelpLink(self, value): ...

    @property
    def InnerException(self): ...

    @InnerException.setter
    def InnerException(self, value): ...

    @property
    def Message(self): ...

    @Message.setter
    def Message(self, value): ...

    def Overloads(self, *args, **kwargs) -> Any: ...
    def SerializeObjectState(self, *args, **kwargs) -> Any: ...

    @property
    def Source(self): ...

    @Source.setter
    def Source(self, value): ...

    @property
    def StackTrace(self): ...

    @StackTrace.setter
    def StackTrace(self, value): ...

    @property
    def TargetSite(self): ...

    @TargetSite.setter
    def TargetSite(self, value): ...

    def ToString(self) -> str: ...
    def add_SerializeObjectState(self, _: Any) -> None: ...
    def args(self, *args, **kwargs) -> Any: ...
    def get_Data(self) -> System.Collections.IDictionary: ...
    def get_HResult(self) -> int: ...
    def get_HelpLink(self) -> str: ...
    def get_InnerException(self) -> Exception: ...
    def get_Message(self) -> str: ...
    def get_Source(self) -> str: ...
    def get_StackTrace(self) -> str: ...
    def get_TargetSite(self) -> System.Reflection.MethodBase: ...
    def remove_SerializeObjectState(self, _: Any) -> None: ...
    def set_HResult(self, _: int) -> None: ...
    def set_HelpLink(self, _: str) -> None: ...
    def set_Source(self, _: str) -> None: ...
    def with_traceback(self, *args, **kwargs) -> Any: ...


class MethodNotSupportedException:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Data(self): ...

    @Data.setter
    def Data(self, value): ...

    def GetBaseException(self) -> Exception: ...

    def GetObjectData(
            self,
            _: System.Runtime.Serialization.SerializationInfo,
            __: System.Runtime.Serialization.StreamingContext,
            ) -> None: ...

    def GetType(self) -> Type: ...

    @property
    def HResult(self): ...

    @HResult.setter
    def HResult(self, value): ...

    @property
    def HelpLink(self): ...

    @HelpLink.setter
    def HelpLink(self, value): ...

    @property
    def InnerException(self): ...

    @InnerException.setter
    def InnerException(self, value): ...

    @property
    def Message(self): ...

    @Message.setter
    def Message(self, value): ...

    def Overloads(self, *args, **kwargs) -> Any: ...
    def SerializeObjectState(self, *args, **kwargs) -> Any: ...

    @property
    def Source(self): ...

    @Source.setter
    def Source(self, value): ...

    @property
    def StackTrace(self): ...

    @StackTrace.setter
    def StackTrace(self, value): ...

    @property
    def TargetSite(self): ...

    @TargetSite.setter
    def TargetSite(self, value): ...

    def ToString(self) -> str: ...
    def add_SerializeObjectState(self, _: Any) -> None: ...
    def args(self, *args, **kwargs) -> Any: ...
    def get_Data(self) -> System.Collections.IDictionary: ...
    def get_HResult(self) -> int: ...
    def get_HelpLink(self) -> str: ...
    def get_InnerException(self) -> Exception: ...
    def get_Message(self) -> str: ...
    def get_Source(self) -> str: ...
    def get_StackTrace(self) -> str: ...
    def get_TargetSite(self) -> System.Reflection.MethodBase: ...
    def remove_SerializeObjectState(self, _: Any) -> None: ...
    def set_HResult(self, _: int) -> None: ...
    def set_HelpLink(self, _: str) -> None: ...
    def set_Source(self, _: str) -> None: ...
    def with_traceback(self, *args, **kwargs) -> Any: ...


class NoClickablePointException:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Data(self): ...

    @Data.setter
    def Data(self, value): ...

    def GetBaseException(self) -> Exception: ...

    def GetObjectData(
            self,
            _: System.Runtime.Serialization.SerializationInfo,
            __: System.Runtime.Serialization.StreamingContext,
            ) -> None: ...

    def GetType(self) -> Type: ...

    @property
    def HResult(self): ...

    @HResult.setter
    def HResult(self, value): ...

    @property
    def HelpLink(self): ...

    @HelpLink.setter
    def HelpLink(self, value): ...

    @property
    def InnerException(self): ...

    @InnerException.setter
    def InnerException(self, value): ...

    @property
    def Message(self): ...

    @Message.setter
    def Message(self, value): ...

    def Overloads(self, *args, **kwargs) -> Any: ...
    def SerializeObjectState(self, *args, **kwargs) -> Any: ...

    @property
    def Source(self): ...

    @Source.setter
    def Source(self, value): ...

    @property
    def StackTrace(self): ...

    @StackTrace.setter
    def StackTrace(self, value): ...

    @property
    def TargetSite(self): ...

    @TargetSite.setter
    def TargetSite(self, value): ...

    def ToString(self) -> str: ...
    def add_SerializeObjectState(self, _: Any) -> None: ...
    def args(self, *args, **kwargs) -> Any: ...
    def get_Data(self) -> System.Collections.IDictionary: ...
    def get_HResult(self) -> int: ...
    def get_HelpLink(self) -> str: ...
    def get_InnerException(self) -> Exception: ...
    def get_Message(self) -> str: ...
    def get_Source(self) -> str: ...
    def get_StackTrace(self) -> str: ...
    def get_TargetSite(self) -> System.Reflection.MethodBase: ...
    def remove_SerializeObjectState(self, _: Any) -> None: ...
    def set_HResult(self, _: int) -> None: ...
    def set_HelpLink(self, _: str) -> None: ...
    def set_Source(self, _: str) -> None: ...
    def with_traceback(self, *args, **kwargs) -> Any: ...


class NotCachedException:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Data(self): ...

    @Data.setter
    def Data(self, value): ...

    def GetBaseException(self) -> Exception: ...

    def GetObjectData(
            self,
            _: System.Runtime.Serialization.SerializationInfo,
            __: System.Runtime.Serialization.StreamingContext,
            ) -> None: ...

    def GetType(self) -> Type: ...

    @property
    def HResult(self): ...

    @HResult.setter
    def HResult(self, value): ...

    @property
    def HelpLink(self): ...

    @HelpLink.setter
    def HelpLink(self, value): ...

    @property
    def InnerException(self): ...

    @InnerException.setter
    def InnerException(self, value): ...

    @property
    def Message(self): ...

    @Message.setter
    def Message(self, value): ...

    def Overloads(self, *args, **kwargs) -> Any: ...
    def SerializeObjectState(self, *args, **kwargs) -> Any: ...

    @property
    def Source(self): ...

    @Source.setter
    def Source(self, value): ...

    @property
    def StackTrace(self): ...

    @StackTrace.setter
    def StackTrace(self, value): ...

    @property
    def TargetSite(self): ...

    @TargetSite.setter
    def TargetSite(self, value): ...

    def ToString(self) -> str: ...
    def add_SerializeObjectState(self, _: Any) -> None: ...
    def args(self, *args, **kwargs) -> Any: ...
    def get_Data(self) -> System.Collections.IDictionary: ...
    def get_HResult(self) -> int: ...
    def get_HelpLink(self) -> str: ...
    def get_InnerException(self) -> Exception: ...
    def get_Message(self) -> str: ...
    def get_Source(self) -> str: ...
    def get_StackTrace(self) -> str: ...
    def get_TargetSite(self) -> System.Reflection.MethodBase: ...
    def remove_SerializeObjectState(self, _: Any) -> None: ...
    def set_HResult(self, _: int) -> None: ...
    def set_HelpLink(self, _: str) -> None: ...
    def set_Source(self, _: str) -> None: ...
    def with_traceback(self, *args, **kwargs) -> Any: ...


class NotSupportedByFrameworkException:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Data(self): ...

    @Data.setter
    def Data(self, value): ...

    def GetBaseException(self) -> Exception: ...

    def GetObjectData(
            self,
            _: System.Runtime.Serialization.SerializationInfo,
            __: System.Runtime.Serialization.StreamingContext,
            ) -> None: ...

    def GetType(self) -> Type: ...

    @property
    def HResult(self): ...

    @HResult.setter
    def HResult(self, value): ...

    @property
    def HelpLink(self): ...

    @HelpLink.setter
    def HelpLink(self, value): ...

    @property
    def InnerException(self): ...

    @InnerException.setter
    def InnerException(self, value): ...

    @property
    def Message(self): ...

    @Message.setter
    def Message(self, value): ...

    def Overloads(self, *args, **kwargs) -> Any: ...
    def SerializeObjectState(self, *args, **kwargs) -> Any: ...

    @property
    def Source(self): ...

    @Source.setter
    def Source(self, value): ...

    @property
    def StackTrace(self): ...

    @StackTrace.setter
    def StackTrace(self, value): ...

    @property
    def TargetSite(self): ...

    @TargetSite.setter
    def TargetSite(self, value): ...

    def ToString(self) -> str: ...
    def add_SerializeObjectState(self, _: Any) -> None: ...
    def args(self, *args, **kwargs) -> Any: ...
    def get_Data(self) -> System.Collections.IDictionary: ...
    def get_HResult(self) -> int: ...
    def get_HelpLink(self) -> str: ...
    def get_InnerException(self) -> Exception: ...
    def get_Message(self) -> str: ...
    def get_Source(self) -> str: ...
    def get_StackTrace(self) -> str: ...
    def get_TargetSite(self) -> System.Reflection.MethodBase: ...
    def remove_SerializeObjectState(self, _: Any) -> None: ...
    def set_HResult(self, _: int) -> None: ...
    def set_HelpLink(self, _: str) -> None: ...
    def set_Source(self, _: str) -> None: ...
    def with_traceback(self, *args, **kwargs) -> Any: ...


class NotSupportedException:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Data(self): ...

    @Data.setter
    def Data(self, value): ...

    def GetBaseException(self) -> Exception: ...

    def GetObjectData(
            self,
            _: System.Runtime.Serialization.SerializationInfo,
            __: System.Runtime.Serialization.StreamingContext,
            ) -> None: ...

    def GetType(self) -> Type: ...

    @property
    def HResult(self): ...

    @HResult.setter
    def HResult(self, value): ...

    @property
    def HelpLink(self): ...

    @HelpLink.setter
    def HelpLink(self, value): ...

    @property
    def InnerException(self): ...

    @InnerException.setter
    def InnerException(self, value): ...

    @property
    def Message(self): ...

    @Message.setter
    def Message(self, value): ...

    def Overloads(self, *args, **kwargs) -> Any: ...
    def SerializeObjectState(self, *args, **kwargs) -> Any: ...

    @property
    def Source(self): ...

    @Source.setter
    def Source(self, value): ...

    @property
    def StackTrace(self): ...

    @StackTrace.setter
    def StackTrace(self, value): ...

    @property
    def TargetSite(self): ...

    @TargetSite.setter
    def TargetSite(self, value): ...

    def ToString(self) -> str: ...
    def add_SerializeObjectState(self, _: Any) -> None: ...
    def args(self, *args, **kwargs) -> Any: ...
    def get_Data(self) -> System.Collections.IDictionary: ...
    def get_HResult(self) -> int: ...
    def get_HelpLink(self) -> str: ...
    def get_InnerException(self) -> Exception: ...
    def get_Message(self) -> str: ...
    def get_Source(self) -> str: ...
    def get_StackTrace(self) -> str: ...
    def get_TargetSite(self) -> System.Reflection.MethodBase: ...
    def remove_SerializeObjectState(self, _: Any) -> None: ...
    def set_HResult(self, _: int) -> None: ...
    def set_HelpLink(self, _: str) -> None: ...
    def set_Source(self, _: str) -> None: ...
    def with_traceback(self, *args, **kwargs) -> Any: ...


class PatternNotCachedException:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Data(self): ...

    @Data.setter
    def Data(self, value): ...

    def GetBaseException(self) -> Exception: ...

    def GetObjectData(
            self,
            _: System.Runtime.Serialization.SerializationInfo,
            __: System.Runtime.Serialization.StreamingContext,
            ) -> None: ...

    def GetType(self) -> Type: ...

    @property
    def HResult(self): ...

    @HResult.setter
    def HResult(self, value): ...

    @property
    def HelpLink(self): ...

    @HelpLink.setter
    def HelpLink(self, value): ...

    @property
    def InnerException(self): ...

    @InnerException.setter
    def InnerException(self, value): ...

    @property
    def Message(self): ...

    @Message.setter
    def Message(self, value): ...

    def Overloads(self, *args, **kwargs) -> Any: ...

    @property
    def Pattern(self): ...

    @Pattern.setter
    def Pattern(self, value): ...

    def SerializeObjectState(self, *args, **kwargs) -> Any: ...

    @property
    def Source(self): ...

    @Source.setter
    def Source(self, value): ...

    @property
    def StackTrace(self): ...

    @StackTrace.setter
    def StackTrace(self, value): ...

    @property
    def TargetSite(self): ...

    @TargetSite.setter
    def TargetSite(self, value): ...

    def ToString(self) -> str: ...
    def add_SerializeObjectState(self, _: Any) -> None: ...
    def args(self, *args, **kwargs) -> Any: ...
    def get_Data(self) -> System.Collections.IDictionary: ...
    def get_HResult(self) -> int: ...
    def get_HelpLink(self) -> str: ...
    def get_InnerException(self) -> Exception: ...
    def get_Message(self) -> str: ...
    def get_Pattern(self) -> PatternId: ...
    def get_Source(self) -> str: ...
    def get_StackTrace(self) -> str: ...
    def get_TargetSite(self) -> System.Reflection.MethodBase: ...
    def remove_SerializeObjectState(self, _: Any) -> None: ...
    def set_HResult(self, _: int) -> None: ...
    def set_HelpLink(self, _: str) -> None: ...
    def set_Source(self, _: str) -> None: ...
    def with_traceback(self, *args, **kwargs) -> Any: ...


class PatternNotSupportedException:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Data(self): ...

    @Data.setter
    def Data(self, value): ...

    def GetBaseException(self) -> Exception: ...

    def GetObjectData(
            self,
            _: System.Runtime.Serialization.SerializationInfo,
            __: System.Runtime.Serialization.StreamingContext,
            ) -> None: ...

    def GetType(self) -> Type: ...

    @property
    def HResult(self): ...

    @HResult.setter
    def HResult(self, value): ...

    @property
    def HelpLink(self): ...

    @HelpLink.setter
    def HelpLink(self, value): ...

    @property
    def InnerException(self): ...

    @InnerException.setter
    def InnerException(self, value): ...

    @property
    def Message(self): ...

    @Message.setter
    def Message(self, value): ...

    def Overloads(self, *args, **kwargs) -> Any: ...

    @property
    def Pattern(self): ...

    @Pattern.setter
    def Pattern(self, value): ...

    def SerializeObjectState(self, *args, **kwargs) -> Any: ...

    @property
    def Source(self): ...

    @Source.setter
    def Source(self, value): ...

    @property
    def StackTrace(self): ...

    @StackTrace.setter
    def StackTrace(self, value): ...

    @property
    def TargetSite(self): ...

    @TargetSite.setter
    def TargetSite(self, value): ...

    def ToString(self) -> str: ...
    def add_SerializeObjectState(self, _: Any) -> None: ...
    def args(self, *args, **kwargs) -> Any: ...
    def get_Data(self) -> System.Collections.IDictionary: ...
    def get_HResult(self) -> int: ...
    def get_HelpLink(self) -> str: ...
    def get_InnerException(self) -> Exception: ...
    def get_Message(self) -> str: ...
    def get_Pattern(self) -> PatternId: ...
    def get_Source(self) -> str: ...
    def get_StackTrace(self) -> str: ...
    def get_TargetSite(self) -> System.Reflection.MethodBase: ...
    def remove_SerializeObjectState(self, _: Any) -> None: ...
    def set_HResult(self, _: int) -> None: ...
    def set_HelpLink(self, _: str) -> None: ...
    def set_Source(self, _: str) -> None: ...
    def with_traceback(self, *args, **kwargs) -> Any: ...


class PropertyNotCachedException:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Data(self): ...

    @Data.setter
    def Data(self, value): ...

    def GetBaseException(self) -> Exception: ...

    def GetObjectData(
            self,
            _: System.Runtime.Serialization.SerializationInfo,
            __: System.Runtime.Serialization.StreamingContext,
            ) -> None: ...

    def GetType(self) -> Type: ...

    @property
    def HResult(self): ...

    @HResult.setter
    def HResult(self, value): ...

    @property
    def HelpLink(self): ...

    @HelpLink.setter
    def HelpLink(self, value): ...

    @property
    def InnerException(self): ...

    @InnerException.setter
    def InnerException(self, value): ...

    @property
    def Message(self): ...

    @Message.setter
    def Message(self, value): ...

    def Overloads(self, *args, **kwargs) -> Any: ...

    @property
    def Property(self): ...

    @Property.setter
    def Property(self, value): ...

    def SerializeObjectState(self, *args, **kwargs) -> Any: ...

    @property
    def Source(self): ...

    @Source.setter
    def Source(self, value): ...

    @property
    def StackTrace(self): ...

    @StackTrace.setter
    def StackTrace(self, value): ...

    @property
    def TargetSite(self): ...

    @TargetSite.setter
    def TargetSite(self, value): ...

    def ToString(self) -> str: ...
    def add_SerializeObjectState(self, _: Any) -> None: ...
    def args(self, *args, **kwargs) -> Any: ...
    def get_Data(self) -> System.Collections.IDictionary: ...
    def get_HResult(self) -> int: ...
    def get_HelpLink(self) -> str: ...
    def get_InnerException(self) -> Exception: ...
    def get_Message(self) -> str: ...
    def get_Property(self) -> PropertyId: ...
    def get_Source(self) -> str: ...
    def get_StackTrace(self) -> str: ...
    def get_TargetSite(self) -> System.Reflection.MethodBase: ...
    def remove_SerializeObjectState(self, _: Any) -> None: ...
    def set_HResult(self, _: int) -> None: ...
    def set_HelpLink(self, _: str) -> None: ...
    def set_Source(self, _: str) -> None: ...
    def with_traceback(self, *args, **kwargs) -> Any: ...


class PropertyNotSupportedException:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Data(self): ...

    @Data.setter
    def Data(self, value): ...

    def GetBaseException(self) -> Exception: ...

    def GetObjectData(
            self,
            _: System.Runtime.Serialization.SerializationInfo,
            __: System.Runtime.Serialization.StreamingContext,
            ) -> None: ...

    def GetType(self) -> Type: ...

    @property
    def HResult(self): ...

    @HResult.setter
    def HResult(self, value): ...

    @property
    def HelpLink(self): ...

    @HelpLink.setter
    def HelpLink(self, value): ...

    @property
    def InnerException(self): ...

    @InnerException.setter
    def InnerException(self, value): ...

    @property
    def Message(self): ...

    @Message.setter
    def Message(self, value): ...

    def Overloads(self, *args, **kwargs) -> Any: ...

    @property
    def Property(self): ...

    @Property.setter
    def Property(self, value): ...

    def SerializeObjectState(self, *args, **kwargs) -> Any: ...

    @property
    def Source(self): ...

    @Source.setter
    def Source(self, value): ...

    @property
    def StackTrace(self): ...

    @StackTrace.setter
    def StackTrace(self, value): ...

    @property
    def TargetSite(self): ...

    @TargetSite.setter
    def TargetSite(self, value): ...

    def ToString(self) -> str: ...
    def add_SerializeObjectState(self, _: Any) -> None: ...
    def args(self, *args, **kwargs) -> Any: ...
    def get_Data(self) -> System.Collections.IDictionary: ...
    def get_HResult(self) -> int: ...
    def get_HelpLink(self) -> str: ...
    def get_InnerException(self) -> Exception: ...
    def get_Message(self) -> str: ...
    def get_Property(self) -> PropertyId: ...
    def get_Source(self) -> str: ...
    def get_StackTrace(self) -> str: ...
    def get_TargetSite(self) -> System.Reflection.MethodBase: ...
    def remove_SerializeObjectState(self, _: Any) -> None: ...
    def set_HResult(self, _: int) -> None: ...
    def set_HelpLink(self, _: str) -> None: ...
    def set_Source(self, _: str) -> None: ...
    def with_traceback(self, *args, **kwargs) -> Any: ...


class ProxyAssemblyNotLoadedException:

    def __init__(self, *args, **kwargs) -> Any: ...

    @property
    def Data(self): ...

    @Data.setter
    def Data(self, value): ...

    def GetBaseException(self) -> Exception: ...

    def GetObjectData(
            self,
            _: System.Runtime.Serialization.SerializationInfo,
            __: System.Runtime.Serialization.StreamingContext,
            ) -> None: ...

    def GetType(self) -> Type: ...

    @property
    def HResult(self): ...

    @HResult.setter
    def HResult(self, value): ...

    @property
    def HelpLink(self): ...

    @HelpLink.setter
    def HelpLink(self, value): ...

    @property
    def InnerException(self): ...

    @InnerException.setter
    def InnerException(self, value): ...

    @property
    def Message(self): ...

    @Message.setter
    def Message(self, value): ...

    def Overloads(self, *args, **kwargs) -> Any: ...
    def SerializeObjectState(self, *args, **kwargs) -> Any: ...

    @property
    def Source(self): ...

    @Source.setter
    def Source(self, value): ...

    @property
    def StackTrace(self): ...

    @StackTrace.setter
    def StackTrace(self, value): ...

    @property
    def TargetSite(self): ...

    @TargetSite.setter
    def TargetSite(self, value): ...

    def ToString(self) -> str: ...
    def add_SerializeObjectState(self, _: Any) -> None: ...
    def args(self, *args, **kwargs) -> Any: ...
    def get_Data(self) -> System.Collections.IDictionary: ...
    def get_HResult(self) -> int: ...
    def get_HelpLink(self) -> str: ...
    def get_InnerException(self) -> Exception: ...
    def get_Message(self) -> str: ...
    def get_Source(self) -> str: ...
    def get_StackTrace(self) -> str: ...
    def get_TargetSite(self) -> System.Reflection.MethodBase: ...
    def remove_SerializeObjectState(self, _: Any) -> None: ...
    def set_HResult(self, _: int) -> None: ...
    def set_HelpLink(self, _: str) -> None: ...
    def set_Source(self, _: str) -> None: ...
    def with_traceback(self, *args, **kwargs) -> Any: ...
